import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { api } from "./api";
import type { Session } from "./auth";
import type { Catalog, Customer } from "./types";
import { formatMoney } from "./types";
import { createIdempotencyTracker } from "./idempotency";
import { selectedFaultNames, toggleFault } from "./faultSelection";

export function Intake({ session, onDone }: { session: Session; onDone: () => void }) {
  const [catalog, setCatalog] = useState<Catalog | null>(null); const [customer, setCustomer] = useState<Customer | null>(null); const [phone, setPhone] = useState(""); const [brandQuery, setBrandQuery] = useState(""); const [selectedFaults, setSelectedFaults] = useState<string[]>([]); const [unlockKind, setUnlockKind] = useState<"" | "PIN" | "PATTERN">(""); const [pattern, setPattern] = useState<number[]>([]); const [estimate, setEstimate] = useState(0); const [deposit, setDeposit] = useState(0); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const pendingRequest = useRef(createIdempotencyTracker());
  useEffect(() => { api<Catalog>("/catalog", {}, session.token).then(setCatalog).catch((e) => setMessage(e.message)); }, [session.token]);
  useEffect(() => { if (phone.replace(/\D/g, "").length < 10) return setCustomer(null); const timer = setTimeout(() => api<Customer | null>(`/customers/search?phone=${encodeURIComponent(phone)}`, {}, session.token).then(setCustomer).catch(() => setCustomer(null)), 350); return () => clearTimeout(timer); }, [phone, session.token]);
  const remaining = useMemo(() => Math.max(0, estimate - deposit), [estimate, deposit]);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setMessage("");
    const d = new FormData(event.currentTarget);
    const payload = { branchId: d.get("branchId"), customer: { name: d.get("customerName"), phone, whatsappPhone: d.get("whatsappPhone") || undefined, isRegular: d.get("regular") === "on", notes: d.get("customerNotes") || undefined }, device: { brandId: d.get("brandId"), model: d.get("model"), color: d.get("color") || undefined, imei: d.get("imei") || undefined }, ...(unlockKind ? { unlock: { kind: unlockKind, value: unlockKind === "PATTERN" ? pattern.join("-") : d.get("unlockValue") } } : {}), reportedFault: d.get("reportedFault"), faultPresetIds: selectedFaults, estimatedCost: estimate.toFixed(2), deposit: deposit.toFixed(2), paymentMethod: d.get("paymentMethod") };
    const fingerprint = JSON.stringify(payload);
    const idempotencyKey = pendingRequest.current.keyFor(fingerprint);
    try {
      const result = await api<{ repairNumber: string }>("/repairs/intake", { method: "POST", headers: { "idempotency-key": idempotencyKey }, body: fingerprint }, session.token);
      pendingRequest.current.clear();
      setMessage(`تم استلام الجهاز بنجاح · ${result.repairNumber}`); setTimeout(onDone, 1400);
    } catch (e) { setMessage((e as Error).message); } finally { setBusy(false); }
  }  if (!catalog) return <div className="loading">جارٍ تجهيز شاشة الاستلام…</div>;
  const brands = catalog.brands.filter((brand) => brand.name.toLowerCase().includes(brandQuery.toLowerCase()));
  return <><header><div><span className="eyebrow">عملية جديدة</span><h1>استلام جهاز</h1></div><button className="ghost" onClick={onDone}>رجوع</button></header><form className="intake" onSubmit={submit}>
    <section className="panel"><h2><span>01</span> بيانات العميل</h2><div className="grid"><label>رقم الهاتف<input value={phone} onChange={(e) => setPhone(e.target.value)} required inputMode="tel" placeholder="01xxxxxxxxx" /></label><label>اسم العميل<input name="customerName" key={customer?.id ?? "new"} defaultValue={customer?.name} required placeholder="الاسم بالكامل" /></label><label>رقم واتساب<input name="whatsappPhone" key={`${customer?.id}-wa`} defaultValue={customer?.whatsappPhone ?? phone} /></label><label>الفرع<select name="branchId" required defaultValue={session.user.branchId ?? catalog.branches[0]?.id}>{catalog.branches.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="check"><input name="regular" type="checkbox" defaultChecked={customer?.isRegular} /> عميل دائم</label><label className="wide">ملاحظات العميل<input name="customerNotes" defaultValue={customer?.notes} /></label></div>{customer && <div className="known-customer"><b>عميل مسجل</b><span>آخر الأجهزة: {customer.repairs?.map((r) => r.repairNumber).join("، ") || "لا يوجد"}</span></div>}</section>
    <section className="panel"><h2><span>02</span> بيانات الجهاز</h2><div className="grid"><label>بحث الماركة<input value={brandQuery} onChange={(e) => setBrandQuery(e.target.value)} placeholder="اكتب اسم الماركة" /></label><label>الماركة<select name="brandId" required defaultValue=""><option value="" disabled>اختر الماركة</option>{brands.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>الموديل<input name="model" required /></label><label>اللون<input name="color" /></label><label>IMEI / Serial<input name="imei" dir="ltr" /></label></div><div className="unlock"><b>بيانات فتح الجهاز <small>مشفرة وتُحذف عند التسليم</small></b><div><button type="button" className={unlockKind === "PIN" ? "selected" : ""} onClick={() => setUnlockKind("PIN")}>PIN / كلمة مرور</button><button type="button" className={unlockKind === "PATTERN" ? "selected" : ""} onClick={() => setUnlockKind("PATTERN")}>نمط القفل</button><button type="button" onClick={() => { setUnlockKind(""); setPattern([]); }}>بدون</button></div>{unlockKind === "PIN" && <input name="unlockValue" type="password" required placeholder="أدخل الرمز" />}{unlockKind === "PATTERN" && <div className="pattern" aria-label="نمط فتح الجهاز">{[1,2,3,4,5,6,7,8,9].map((point) => <button type="button" key={point} className={pattern.includes(point) ? "selected" : ""} onClick={() => setPattern((value) => value.includes(point) ? value.filter((x) => x !== point) : [...value, point])}>{point}</button>)}</div>}</div></section>
    <section className="panel"><h2><span>03</span> وصف العطل</h2><textarea name="reportedFault" required placeholder="اكتب وصف العميل للعطل بالتفصيل…" /><div className="chips">{catalog.faults.map((fault) => <button type="button" key={fault.id} aria-pressed={selectedFaults.includes(fault.id)} className={selectedFaults.includes(fault.id) ? "selected" : ""} onClick={() => setSelectedFaults((value) => toggleFault(value, fault.id))}>{fault.name}</button>)}</div><div className="selected-faults" aria-live="polite"><b>الأعطال المحددة:</b> {selectedFaultNames(selectedFaults, catalog.faults).join("، ") || "لا توجد أعطال محددة"}</div></section>
    <section className="panel"><h2><span>04</span> التقدير المبدئي</h2><div className="money-grid"><label>التكلفة التقديرية<input type="number" min="0" step="0.01" value={estimate} onChange={(e) => setEstimate(Number(e.target.value))} /></label><label>العربون<input type="number" min="0" max={estimate} step="0.01" value={deposit} onChange={(e) => setDeposit(Number(e.target.value))} /></label><label>طريقة الدفع<select name="paymentMethod"><option value="CASH">نقدي</option><option value="VODAFONE_CASH">فودافون كاش</option><option value="INSTAPAY">إنستا باي</option><option value="CARD">بطاقة</option><option value="BANK_TRANSFER">تحويل بنكي</option><option value="OTHER">أخرى</option></select></label><div><span>المتبقي التقديري</span><strong>{formatMoney(remaining)}</strong></div></div><p className="hint">هذا تقدير أولي؛ يعتمد السعر النهائي بعد فحص الورشة وموافقة العميل.</p></section>{message && <div className={message.startsWith("تم") ? "success" : "error"}>{message}</div>}<footer className="form-footer"><button type="button" className="ghost" onClick={onDone}>إلغاء</button><button className="primary" disabled={busy || deposit > estimate || (unlockKind === "PATTERN" && pattern.length < 2)}>{busy ? "جارٍ الحفظ…" : "استلام الجهاز وطباعة الإيصال"}</button></footer>
  </form></>;
}


