import { useEffect, useState, type FormEvent } from "react";
import { invoke } from "@tauri-apps/api/core";
import { api } from "./api";
import type { Session } from "./auth";
import { getPrinterConfig, isTauriDesktop, listPrinters, savePrinterConfig, type PrinterInfo } from "./printer";
import { renderPrintDocument } from "./printDocument";

type Workstation = { id: string; name: string; type: string; defaultPage: string; branch: { name: string; code: string } };
const sampleReceipt = { shopName: "مركز الصيانة", branch: "الفرع الرئيسي", repairNumber: "TEST-0001", customer: "طباعة تجريبية", phone: "01000000000", brand: "Samsung", model: "A54", fault: "اختبار الطابعة العربية", selectedFaults: ["الشاشة", "الشحن"], estimatedCost: 500, deposit: 100, estimatedRemaining: 400, qrValue: "https://mobile-shop-maintenance.vercel.app" };
const sampleLabel = { repairNumber: "TEST-0001", brand: "Samsung", model: "A54", customer: "طباعة تجريبية", intakeDate: new Date().toISOString(), qrValue: "https://mobile-shop-maintenance.vercel.app" };
export function PrinterWorkstationSettings({ session }: { session: Session }) {
  const [printers, setPrinters] = useState<PrinterInfo[]>([]); const [workstations, setWorkstations] = useState<Workstation[]>([]); const [message, setMessage] = useState(""); const current = getPrinterConfig(session);
  useEffect(() => { api<Workstation[]>("/settings/workstations", {}, session.token).then(setWorkstations).catch((e) => setMessage(e.message)); if (isTauriDesktop()) listPrinters().then(setPrinters).catch((error) => setMessage(String(error))); }, [session.token]);
  function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const workstationId = String(data.get("workstationId")); const workstation = workstations.find((item) => item.id === workstationId); savePrinterConfig(session, { workstationId, receiptPrinter: String(data.get("receiptPrinter") ?? ""), labelPrinter: String(data.get("labelPrinter") ?? ""), paperSize: data.get("paperSize") === "58mm" ? "58mm" : "80mm", labelWidthMm: Math.min(100, Math.max(20, Number(data.get("labelWidthMm") ?? 50))), labelHeightMm: Math.min(100, Math.max(15, Number(data.get("labelHeightMm") ?? 30))), copies: Math.min(10, Math.max(1, Number(data.get("copies") ?? 1))), autoPrintReception: data.get("autoPrintReception") === "on", autoPrintDelivery: data.get("autoPrintDelivery") === "on", autoPrintLabel: data.get("autoPrintLabel") === "on", defaultPage: workstation?.defaultPage as any }); setMessage("تم حفظ إعدادات محطة الطباعة"); }
  async function browserPreview(kind: "RECEIPT" | "LABEL") { const data = kind === "LABEL" ? sampleLabel : { ...sampleReceipt, logoUrl: undefined }; const html = await renderPrintDocument({ kind, payload: data, paperWidth: current?.paperSize ?? "80mm", labelWidthMm: current?.labelWidthMm, labelHeightMm: current?.labelHeightMm }); const win = window.open("", "_blank", "width=460,height=720"); if (!win) return setMessage("تعذر فتح معاينة الطباعة. اسمح بالنوافذ المنبثقة"); win.document.write(html); win.document.close(); }
  async function test(kind: "RECEIPT" | "LABEL") { const cfg = getPrinterConfig(session); const printerName = kind === "LABEL" ? cfg?.labelPrinter : cfg?.receiptPrinter; if (!isTauriDesktop()) return browserPreview(kind); if (!cfg || !printerName) return setMessage("اختر الطابعة واحفظ الإعدادات أولاً"); try { await invoke("print_job", { request: { printerName, kind, copies: 1, payload: kind === "LABEL" ? sampleLabel : { ...sampleReceipt, paperWidth: cfg.paperSize } } }); setMessage(kind === "LABEL" ? "تم إرسال ملصق الاختبار للطابعة بنجاح" : "تم إرسال إيصال الاختبار للطابعة بنجاح"); } catch (error) { setMessage(`فشلت الطباعة: ${String(error)}`); } }
  return <form className="panel" onSubmit={save}><h2>محطة الطباعة</h2>{message && <div className={message.startsWith("تم") ? "success" : "error"}>{message}</div>}<label>محطة العمل<select name="workstationId" required defaultValue={current?.workstationId ?? ""}><option value="" disabled>اختر المحطة</option>{workstations.map((x) => <option value={x.id} key={x.id}>{x.branch.name} · {x.name}</option>)}</select></label>{!isTauriDesktop() && <p className="hint">المتصفح يوفر معاينة وطباعة نظامية. اكتشاف طابعات Windows والطباعة التلقائية متاحان داخل تطبيق سطح المكتب.</p>}<label>طابعة الإيصال<select name="receiptPrinter" defaultValue={current?.receiptPrinter ?? printers.find((item) => item.isDefault)?.name ?? ""}><option value="">بدون طابعة</option>{printers.map((item) => <option key={item.name} value={item.name} disabled={item.isOffline}>{item.name}{item.isDefault ? " (افتراضية)" : ""}{item.isOffline ? " (غير متصلة)" : ""}</option>)}</select></label><label>طابعة الملصق<select name="labelPrinter" defaultValue={current?.labelPrinter ?? ""}><option value="">بدون طابعة</option>{printers.map((item) => <option key={item.name} value={item.name} disabled={item.isOffline}>{item.name}</option>)}</select></label><label>مقاس الإيصال<select name="paperSize" defaultValue={current?.paperSize ?? "80mm"}><option value="58mm">58mm</option><option value="80mm">80mm</option></select></label><div className="row"><label>عرض الملصق (مم)<input name="labelWidthMm" type="number" min="20" max="100" defaultValue={current?.labelWidthMm ?? 50} /></label><label>ارتفاع الملصق (مم)<input name="labelHeightMm" type="number" min="15" max="100" defaultValue={current?.labelHeightMm ?? 30} /></label></div><label>عدد النسخ<input name="copies" type="number" min="1" max="10" defaultValue={current?.copies ?? 1} /></label><label className="check"><input name="autoPrintReception" type="checkbox" defaultChecked={current?.autoPrintReception ?? true} /> طباعة إيصال الاستلام تلقائيًا</label><label className="check"><input name="autoPrintLabel" type="checkbox" defaultChecked={current?.autoPrintLabel ?? true} /> طباعة الملصق تلقائيًا</label><label className="check"><input name="autoPrintDelivery" type="checkbox" defaultChecked={current?.autoPrintDelivery ?? true} /> طباعة إيصال التسليم تلقائيًا</label><div className="row wrap"><button className="primary">حفظ محطة الطباعة</button><button type="button" className="ghost" onClick={() => test("RECEIPT")}>اختبار الإيصال</button><button type="button" className="ghost" onClick={() => test("LABEL")}>اختبار الملصق</button></div></form>;
}
