import { FormEvent, useEffect, useState } from "react";
import type { Session } from "./auth";
import { getPrinterConfig, isTauriDesktop, listPrinters, savePrinterConfig, type PrinterInfo } from "./printer";

export function PrinterWorkstationSettings({ session }: { session: Session }) {
  const [printers, setPrinters] = useState<PrinterInfo[]>([]); const [message, setMessage] = useState(""); const current = getPrinterConfig(session);
  useEffect(() => { if (isTauriDesktop()) listPrinters().then(setPrinters).catch((error) => setMessage(String(error))); }, []);
  function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); savePrinterConfig(session, { workstationId: current?.workstationId ?? crypto.randomUUID(), receiptPrinter: String(data.get("receiptPrinter") ?? ""), labelPrinter: String(data.get("labelPrinter") ?? ""), paperSize: data.get("paperSize") === "58mm" ? "58mm" : "80mm", copies: Math.min(10, Math.max(1, Number(data.get("copies") ?? 1))), autoPrintReception: data.get("autoPrintReception") === "on", autoPrintDelivery: data.get("autoPrintDelivery") === "on", autoPrintLabel: data.get("autoPrintLabel") === "on" }); setMessage("تم حفظ إعدادات محطة الطباعة"); }
  if (!isTauriDesktop()) return <section className="panel"><h2>محطة الطباعة</h2><p className="hint">اكتشاف الطابعات والطباعة التلقائية متاحان داخل تطبيق Windows فقط.</p></section>;
  return <form className="panel" onSubmit={save}><h2>محطة الطباعة</h2>{message && <div className={message.startsWith("تم") ? "success" : "error"}>{message}</div>}<label>طابعة الإيصال<select name="receiptPrinter" defaultValue={current?.receiptPrinter ?? printers.find((item) => item.isDefault)?.name ?? ""}><option value="">بدون طابعة</option>{printers.map((item) => <option key={item.name} value={item.name} disabled={item.isOffline}>{item.name}{item.isDefault ? " (افتراضية)" : ""}{item.isOffline ? " (غير متصلة)" : ""}</option>)}</select></label><label>طابعة الملصق<select name="labelPrinter" defaultValue={current?.labelPrinter ?? ""}><option value="">بدون طابعة</option>{printers.map((item) => <option key={item.name} value={item.name} disabled={item.isOffline}>{item.name}</option>)}</select></label><label>مقاس الورق<select name="paperSize" defaultValue={current?.paperSize ?? "80mm"}><option value="58mm">58mm</option><option value="80mm">80mm</option></select></label><label>عدد النسخ<input name="copies" type="number" min="1" max="10" defaultValue={current?.copies ?? 1} /></label><label className="check"><input name="autoPrintReception" type="checkbox" defaultChecked={current?.autoPrintReception ?? true} /> طباعة إيصال الاستلام تلقائيًا</label><label className="check"><input name="autoPrintLabel" type="checkbox" defaultChecked={current?.autoPrintLabel ?? true} /> طباعة الملصق تلقائيًا</label><label className="check"><input name="autoPrintDelivery" type="checkbox" defaultChecked={current?.autoPrintDelivery ?? true} /> طباعة إيصال التسليم تلقائيًا</label><button className="primary">حفظ محطة الطباعة</button></form>;
}