import { FormEvent, useEffect, useState } from "react";
import { api, downloadCsv } from "./api";
import type { Session } from "./auth";
import type { CatalogItem } from "./types";
import { PrinterWorkstationSettings } from "./PrinterSettings";
import { LogoPicker } from "./settings-ui";

type Branch = { id: string; name: string; code: string; address?: string; phone?: string; isActive: boolean; isPrimary: boolean };
type Subscription = { status: string; billingCycle: string; startsAt: string; endsAt?: string; plan: { name: string; limits: Record<string, unknown> } } | null;
type OutboxItem = { id: string; repairOrderId: string; type: string; recipient: string; status: string; failureReason?: string; deliveredAt?: string; readAt?: string; createdAt: string };
type WhatsappStatus = { status: string; provider: string; missing: string[]; webhookUrl: string };
const templateFields = [
  ["device_received", "استلام الجهاز"], ["waiting_approval", "طلب الموافقة"], ["under_repair", "قيد الصيانة"], ["ready_for_delivery", "جاهز للتسليم"], ["delivered", "تم التسليم"],
] as const;
const defaults: Record<string, string> = {
  device_received: "مرحباً {customerName}، تم استلام جهازك {brand} {model} في {shopName}. رقم أمر الصيانة: {repairNumber}. متابعة الجهاز: {trackingUrl}",
  waiting_approval: "مرحباً {customerName}، تم فحص جهازك {brand} {model}. التشخيص: {diagnosis}. تكلفة الصيانة: {finalAmount}. الموافقة أو الرفض: {approvalUrl}. المتابعة: {trackingUrl}",
  under_repair: "مرحباً {customerName}، جهازك {brand} {model} رقم {repairNumber} أصبح قيد الصيانة لدى {shopName}. المتابعة: {trackingUrl}",
  ready_for_delivery: "مرحباً {customerName}، جهازك {brand} {model} رقم {repairNumber} جاهز للتسليم من {branchName}. الإجمالي: {finalAmount}. المدفوع: {paidAmount}. {remainingAmount}. المتابعة: {trackingUrl}",
  delivered: "مرحباً {customerName}، تم تسليم جهازك {brand} {model} رقم {repairNumber} بنجاح. شكراً لزيارتكم {shopName}. للتواصل: {shopPhone} {warrantyEndDate}",
};
const previewTemplate = (value: string) => value.replaceAll("{customerName}", "أحمد").replaceAll("{shopName}", "مركز الصيانة").replaceAll("{shopPhone}", "01000000000").replaceAll("{branchName}", "الفرع الرئيسي").replaceAll("{brand}", "Samsung").replaceAll("{model}", "A54").replaceAll("{repairNumber}", "REP-2026-000001").replaceAll("{trackingUrl}", "رابط المتابعة").replaceAll("{approvalUrl}", "رابط الموافقة").replaceAll("{diagnosis}", "تغيير الشاشة").replaceAll("{finalAmount}", "1,500 ج.م").replaceAll("{paidAmount}", "500 ج.م").replaceAll("{remainingAmount}", "المتبقي: 1,000 ج.م").replaceAll("{warrantyEndDate}", "الضمان حتى 1/1/2027");

export function Settings({ session }: { session: Session }) {
  const [brands, setBrands] = useState<CatalogItem[]>([]); const [faults, setFaults] = useState<CatalogItem[]>([]); const [branches, setBranches] = useState<Branch[]>([]); const [shop, setShop] = useState<Record<string, any> | null>(null); const [logo, setLogo] = useState(""); const [templates, setTemplates] = useState<Record<string, string>>(defaults); const [subscription, setSubscription] = useState<Subscription>(null); const [message, setMessage] = useState(""); const [outbox, setOutbox] = useState<OutboxItem[]>([]); const [whatsappStatus, setWhatsappStatus] = useState<WhatsappStatus | null>(null);
  const load = () => Promise.all([api<CatalogItem[]>("/settings/brands", {}, session.token), api<CatalogItem[]>("/settings/faults", {}, session.token), api<Record<string, any>>("/settings/shop", {}, session.token), api<Branch[]>("/settings/branches", {}, session.token), api<Subscription>("/settings/subscription", {}, session.token), api<OutboxItem[]>("/whatsapp/outbox", {}, session.token), api<WhatsappStatus>("/settings/whatsapp/status", {}, session.token)]).then(([b, f, s, br, sub, messages, providerStatus]) => { setBrands(b); setFaults(f); setShop(s); setLogo(s.logoUrl ?? ""); setTemplates({ ...defaults, ...(s.messageTemplates ?? {}) }); setBranches(br); setSubscription(sub); setOutbox(messages); setWhatsappStatus(providerStatus); }).catch((e) => setMessage(e.message));
  useEffect(() => { void load(); }, [session.token]);
  async function add(event: FormEvent<HTMLFormElement>, kind: "brands" | "faults") { event.preventDefault(); const form = event.currentTarget; const d = new FormData(form); try { await api(`/settings/${kind}`, { method: "POST", body: JSON.stringify({ name: d.get("name"), sortOrder: 0, isActive: true }) }, session.token); form.reset(); setMessage("تمت الإضافة"); await load(); } catch (e) { setMessage((e as Error).message); } }
  async function patchCatalog(kind: "brands" | "faults", item: CatalogItem, changes: Record<string, unknown>) { try { await api(`/settings/${kind}/${item.id}`, { method: "PATCH", body: JSON.stringify(changes) }, session.token); await load(); } catch (e) { setMessage((e as Error).message); } }
  async function rename(kind: "brands" | "faults", item: CatalogItem) { const name = window.prompt("الاسم الجديد", item.name); if (name?.trim() && name !== item.name) await patchCatalog(kind, item, { name: name.trim() }); }
  async function saveShop(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const d = new FormData(event.currentTarget); const body = { name: d.get("name"), phone: d.get("phone") || null, whatsapp: d.get("whatsapp") || null, address: d.get("address") || null, logoUrl: logo || null, primaryColor: d.get("primaryColor"), receiptFooter: d.get("receiptFooter") || null, receiptPaperWidth: d.get("receiptPaperWidth"), thermalPrinterSettings: { printer: String(d.get("thermalPrinter") || "default") }, labelPrinterSettings: { printer: String(d.get("labelPrinter") || "default") }, whatsappSettings: { mode: String(d.get("whatsappMode") || "mock") }, workflowSettings: { readyRequiresApproval: String(d.get("readyRequiresApproval") === "on") }, messageTemplates: templates }; try { await api("/settings/shop", { method: "PATCH", body: JSON.stringify(body) }, session.token); setMessage("تم حفظ إعدادات المركز"); await load(); } catch (e) { setMessage((e as Error).message); } }
  async function addBranch(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const d = Object.fromEntries(new FormData(form)); try { await api("/settings/branches", { method: "POST", body: JSON.stringify(d) }, session.token); form.reset(); setMessage("تمت إضافة الفرع"); await load(); } catch (e) { setMessage((e as Error).message); } }
  async function toggleBranch(branch: Branch) { try { await api(`/settings/branches/${branch.id}`, { method: "PATCH", body: JSON.stringify({ isActive: !branch.isActive }) }, session.token); await load(); } catch (e) { setMessage((e as Error).message); } }
  async function processOutbox() { try { const result = await api<{ processed: number; sent: number; failed: number }>("/whatsapp/process", { method: "POST" }, session.token); setMessage(`تمت معالجة ${result.processed} رسالة: ${result.sent} ناجحة، ${result.failed} فاشلة`); await load(); } catch (e) { setMessage((e as Error).message); } }
  async function testWhatsappConfig() { try { await api("/settings/whatsapp/test-config", { method: "POST" }, session.token); setMessage("تم التحقق من اتصال Meta بنجاح"); await load(); } catch (e) { setMessage((e as Error).message); } }
const outboxStatus = (item: OutboxItem) => item.readAt ? "تمت القراءة" : item.deliveredAt ? "تم التسليم" : item.status === "SENT" ? "تم الإرسال" : item.status === "FAILED" ? "فشل الإرسال" : "في انتظار الإرسال";
  async function saveTemplates() { try { await api("/settings/shop", { method: "PATCH", body: JSON.stringify({ messageTemplates: templates }) }, session.token); setMessage("تم حفظ قوالب رسائل واتساب"); await load(); } catch (e) { setMessage((e as Error).message); } }
  async function resendWhatsapp(id: string) { try { await api(`/whatsapp/${id}/resend`, { method: "POST" }, session.token); setMessage("تمت إعادة الرسالة إلى قائمة الإرسال"); await load(); } catch (e) { setMessage((e as Error).message); } }
  async function sendTestMessage(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await api("/settings/whatsapp/test-message", { method: "POST", body: JSON.stringify({ recipient: data.get("recipient"), templateKey: data.get("templateKey") }) }, session.token); setMessage("تم قبول رسالة الاختبار من Meta"); } catch (e) { setMessage((e as Error).message); } }
  async function exportData(kind: "customers" | "repairs" | "payments" | "expenses") { try { const blob = await downloadCsv(`/exports/${kind}.csv`, session.token); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${kind}-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url); setMessage("تم تجهيز ملف التصدير"); } catch (e) { setMessage((e as Error).message); } }
  if (!shop) return <div className="loading">جارٍ تحميل الإعدادات…</div>;
  const statusText = whatsappStatus?.status === "META_CONNECTED" ? "Meta متصل" : whatsappStatus?.status === "META_READY" ? "Meta جاهز" : whatsappStatus?.status === "TEST" ? "وضع تجريبي" : whatsappStatus?.status === "ERROR" ? "الإعداد غير مكتمل" : "واتساب غير مهيأ للإرسال الحقيقي";
  return <><header><div><span className="eyebrow">إدارة النظام</span><h1>إعدادات المركز</h1></div></header>{message && <div className={message.startsWith("تم") ? "success" : "error"}>{message}</div>}<section className="settings-layout">
    <form className="panel settings-general" onSubmit={saveShop}><h2>عام وهوية المركز</h2><div className="settings-fields"><label>اسم المحل<input name="name" defaultValue={shop.name} required /></label><label>الهاتف<input name="phone" defaultValue={shop.phone ?? ""} /></label><label>واتساب<input name="whatsapp" defaultValue={shop.whatsapp ?? ""} /></label><label>العنوان<input name="address" defaultValue={shop.address ?? ""} /></label><label>اللون الرئيسي<input name="primaryColor" type="color" defaultValue={shop.primaryColor ?? "#0f766e"} /></label></div><LogoPicker value={logo} onChange={setLogo} /><h3>الإيصال والطابعات</h3><div className="settings-fields"><label>مقاس الورق<select name="receiptPaperWidth" defaultValue={shop.receiptPaperWidth ?? "80mm"}><option value="58mm">58mm</option><option value="80mm">80mm</option></select></label><label>طابعة الإيصال<input name="thermalPrinter" defaultValue={shop.thermalPrinterSettings?.printer ?? "default"} /></label><label>طابعة الملصق<input name="labelPrinter" defaultValue={shop.labelPrinterSettings?.printer ?? "default"} /></label><label className="wide">تذييل الإيصال<textarea name="receiptFooter" defaultValue={shop.receiptFooter ?? ""} /></label></div><label className="check"><input name="readyRequiresApproval" type="checkbox" defaultChecked={shop.workflowSettings?.readyRequiresApproval !== "false"} /> يتطلب الإصلاح موافقة العميل</label><label>مزود واتساب<select name="whatsappMode" defaultValue={shop.whatsappSettings?.mode ?? "mock"}><option value="mock">تجريبي / Mock</option><option value="meta">Meta</option></select></label><button className="primary">حفظ الإعدادات</button></form>
    <section className="panel"><h2>الفروع</h2><form className="branch-form" onSubmit={addBranch}><input name="name" required placeholder="اسم الفرع" /><input name="code" required placeholder="الكود" /><input name="address" placeholder="العنوان" /><button className="primary">إضافة فرع</button></form><div className="branch-list">{branches.map((branch) => <article key={branch.id}><div><b>{branch.name}</b><span>{branch.code} {branch.isPrimary && "· الرئيسي"}</span><small>{branch.address || "بدون عنوان"}</small></div><button className="ghost" onClick={() => toggleBranch(branch)}>{branch.isActive ? "تعطيل" : "تفعيل"}</button></article>)}</div></section>
    <CatalogEditor title="ماركات الأجهزة" items={brands} kind="brands" add={add} patch={patchCatalog} rename={rename} /><CatalogEditor title="أنواع الأعطال" items={faults} kind="faults" add={add} patch={patchCatalog} rename={rename} />
    <section className="panel whatsapp-settings"><div className="row between"><h2>واتساب</h2><span className={`provider-badge ${whatsappStatus?.status === "META_READY" ? "ready" : ""}`}>{statusText}</span></div>{Boolean(whatsappStatus?.missing.length) && <p className="error compact">الإعدادات الناقصة: {whatsappStatus?.missing.join("، ")}</p>}<label>Webhook URL<input readOnly dir="ltr" value={whatsappStatus?.webhookUrl ?? ""} onFocus={(e) => e.currentTarget.select()} /></label><div className="row wrap"><button type="button" className="ghost" onClick={() => navigator.clipboard.writeText(whatsappStatus?.webhookUrl ?? "")}>نسخ Webhook</button><button type="button" className="ghost" onClick={testWhatsappConfig}>اختبار Meta</button><button type="button" className="primary" onClick={processOutbox}>معالجة القائمة</button></div><form className="compact-form" onSubmit={sendTestMessage}><h3>رسالة اختبار حقيقية</h3><input name="recipient" dir="ltr" required placeholder="201xxxxxxxxx" /><input name="templateKey" dir="ltr" required defaultValue="hello_world" /><button className="ghost">إرسال عبر Meta</button></form><h3>قوالب الرسائل</h3><div className="template-grid">{templateFields.map(([key, label]) => <label key={key}>{label}<textarea value={templates[key] ?? defaults[key] ?? ""} onChange={(e) => setTemplates((current) => ({ ...current, [key]: e.target.value }))} /><small className="template-preview">معاينة: {previewTemplate(templates[key] ?? defaults[key] ?? "")}</small></label>)}</div><button type="button" className="primary" onClick={saveTemplates}>حفظ قوالب الرسائل</button><div className="message-counters"><span>انتظار <b>{outbox.filter((x) => x.status === "QUEUED").length}</b></span><span>أُرسلت <b>{outbox.filter((x) => x.status === "SENT" && !x.deliveredAt).length}</b></span><span>سُلّمت <b>{outbox.filter((x) => Boolean(x.deliveredAt) && !x.readAt).length}</b></span><span>قُرئت <b>{outbox.filter((x) => Boolean(x.readAt)).length}</b></span><span>فشلت <b>{outbox.filter((x) => x.status === "FAILED").length}</b></span></div><div className="message-list">{outbox.slice(0, 20).map((item) => <article key={item.id}><div><b>{item.type.replaceAll("_", " ")}</b><span dir="ltr">{item.recipient}</span><small>{new Date(item.createdAt).toLocaleString("ar-EG")}</small>{item.failureReason && <small className="danger-text">{item.failureReason}</small>}</div><span>{outboxStatus(item)}</span>{item.status === "FAILED" && <button type="button" className="ghost" onClick={() => resendWhatsapp(item.id)}>إعادة المحاولة</button>}</article>)}</div></section>
    <section className="panel"><h2>تصدير البيانات</h2><p className="hint">ملفات CSV معزولة حسب المركز والفرع وصلاحيات المستخدم.</p><div className="row wrap"><button type="button" className="ghost" onClick={() => exportData("customers")}>العملاء</button><button type="button" className="ghost" onClick={() => exportData("repairs")}>أوامر الصيانة</button>{session.user.permissions.includes("report.financial.view") && <><button type="button" className="ghost" onClick={() => exportData("payments")}>المدفوعات</button><button type="button" className="ghost" onClick={() => exportData("expenses")}>المصروفات</button></>}</div></section>
    <section className="panel"><h2>الاشتراك</h2>{subscription ? <><strong>{subscription.plan.name}</strong><p>{subscription.status} · {subscription.billingCycle}</p><small>بداية الاشتراك {new Date(subscription.startsAt).toLocaleDateString("ar-EG")}</small></> : <p>لا يوجد اشتراك مسجل</p>}</section><PrinterWorkstationSettings session={session} />
  </section></>;
}

function CatalogEditor({ title, items, kind, add, patch, rename }: { title: string; items: CatalogItem[]; kind: "brands" | "faults"; add: (event: FormEvent<HTMLFormElement>, kind: "brands" | "faults") => void; patch: (kind: "brands" | "faults", item: CatalogItem, changes: Record<string, unknown>) => void; rename: (kind: "brands" | "faults", item: CatalogItem) => void }) {
  return <section className="panel catalog-editor"><h2>{title}</h2><form className="inline-form" onSubmit={(event) => add(event, kind)}><input name="name" required placeholder="اسم جديد" /><button className="primary">إضافة</button></form><div className="catalog-list">{items.map((item) => <article key={item.id}><span>{item.name}</span><div className="catalog-actions"><button className="ghost" onClick={() => patch(kind, item, { sortOrder: Math.max(0, (item.sortOrder ?? 0) - 1) })} aria-label="رفع">↑</button><button className="ghost" onClick={() => patch(kind, item, { sortOrder: (item.sortOrder ?? 0) + 1 })} aria-label="خفض">↓</button><button className="ghost" onClick={() => rename(kind, item)}>تعديل</button><button className="ghost" onClick={() => patch(kind, item, { isActive: !item.isActive })}>{item.isActive ? "تعطيل" : "تفعيل"}</button></div></article>)}</div></section>;
}
