import { FormEvent, useEffect, useState } from "react";
import { api } from "./api";
import type { Session } from "./auth";
import type { CatalogItem } from "./types";

type Branch = { id: string; name: string; code: string; address?: string; phone?: string; isActive: boolean };
type Subscription = { status: string; billingCycle: string; startsAt: string; endsAt?: string; plan: { name: string; limits: Record<string, unknown> } } | null;

export function Settings({ session }: { session: Session }) {
  const [brands, setBrands] = useState<CatalogItem[]>([]); const [faults, setFaults] = useState<CatalogItem[]>([]); const [branches, setBranches] = useState<Branch[]>([]); const [shop, setShop] = useState<Record<string, any> | null>(null); const [subscription, setSubscription] = useState<Subscription>(null); const [message, setMessage] = useState(""); const [outbox, setOutbox] = useState<{ status: string }[]>([]);
  const load = () => Promise.all([api<CatalogItem[]>("/settings/brands", {}, session.token), api<CatalogItem[]>("/settings/faults", {}, session.token), api<Record<string, any>>("/settings/shop", {}, session.token), api<Branch[]>("/settings/branches", {}, session.token), api<Subscription>("/settings/subscription", {}, session.token), api<{ status: string }[]>("/whatsapp/outbox", {}, session.token)]).then(([b, f, s, br, sub, messages]) => { setBrands(b); setFaults(f); setShop(s); setBranches(br); setSubscription(sub); setOutbox(messages); }).catch((e) => setMessage(e.message));
  useEffect(() => { void load(); }, [session.token]);
  async function add(event: FormEvent<HTMLFormElement>, kind: "brands" | "faults") { event.preventDefault(); const form = event.currentTarget; const d = new FormData(form); try { await api(`/settings/${kind}`, { method: "POST", body: JSON.stringify({ name: d.get("name"), sortOrder: 0, isActive: true }) }, session.token); form.reset(); setMessage("تمت الإضافة"); load(); } catch (e) { setMessage((e as Error).message); } }
  async function patchCatalog(kind: "brands" | "faults", item: CatalogItem, changes: Record<string, unknown>) { try { await api(`/settings/${kind}/${item.id}`, { method: "PATCH", body: JSON.stringify(changes) }, session.token); load(); } catch (e) { setMessage((e as Error).message); } }
  async function rename(kind: "brands" | "faults", item: CatalogItem) { const name = window.prompt("الاسم الجديد", item.name); if (name?.trim() && name !== item.name) await patchCatalog(kind, item, { name: name.trim() }); }
  async function saveShop(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const d = new FormData(event.currentTarget); const body = { name: d.get("name"), phone: d.get("phone") || null, whatsapp: d.get("whatsapp") || null, address: d.get("address") || null, logoUrl: d.get("logoUrl") || null, primaryColor: d.get("primaryColor"), receiptFooter: d.get("receiptFooter") || null, receiptPaperWidth: d.get("receiptPaperWidth"), thermalPrinterSettings: { printer: String(d.get("thermalPrinter") || "default") }, labelPrinterSettings: { printer: String(d.get("labelPrinter") || "default") }, whatsappSettings: { mode: String(d.get("whatsappMode") || "mock") }, workflowSettings: { readyRequiresApproval: String(d.get("readyRequiresApproval") === "on") }, messageTemplates: { received: String(d.get("receivedTemplate") || "") } }; try { await api("/settings/shop", { method: "PATCH", body: JSON.stringify(body) }, session.token); setMessage("تم حفظ إعدادات المركز"); load(); } catch (e) { setMessage((e as Error).message); } }
  async function addBranch(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const d = Object.fromEntries(new FormData(form)); try { await api("/settings/branches", { method: "POST", body: JSON.stringify(d) }, session.token); form.reset(); load(); } catch (e) { setMessage((e as Error).message); } }
  async function toggleBranch(branch: Branch) { try { await api(`/settings/branches/${branch.id}`, { method: "PATCH", body: JSON.stringify({ isActive: !branch.isActive }) }, session.token); load(); } catch (e) { setMessage((e as Error).message); } }
  async function processOutbox() { try { const result = await api<{ processed: number; sent: number; failed: number }>("/whatsapp/process", { method: "POST" }, session.token); setMessage(`تمت معالجة ${result.processed} رسالة: ${result.sent} ناجحة، ${result.failed} فاشلة`); load(); } catch (e) { setMessage((e as Error).message); } }
  if (!shop) return <div className="loading">جارٍ تحميل الإعدادات…</div>;
  return <><header><div><span className="eyebrow">إدارة النظام</span><h1>إعدادات المركز</h1></div></header>{message && <div className={message.startsWith("تم") ? "success" : "error"}>{message}</div>}<section className="settings-grid">
    <form className="panel" onSubmit={saveShop}><h2>عام وهوية المركز</h2><label>اسم المحل<input name="name" defaultValue={shop.name} required /></label><label>اللوجو (URL)<input name="logoUrl" type="url" defaultValue={shop.logoUrl ?? ""} /></label><label>الهاتف<input name="phone" defaultValue={shop.phone ?? ""} /></label><label>واتساب<input name="whatsapp" defaultValue={shop.whatsapp ?? ""} /></label><label>العنوان<input name="address" defaultValue={shop.address ?? ""} /></label><label>اللون الرئيسي<input name="primaryColor" type="color" defaultValue={shop.primaryColor ?? "#0f766e"} /></label><h3>إيصال الاستلام والطابعات</h3><label>مقاس الورق<select name="receiptPaperWidth" defaultValue={shop.receiptPaperWidth ?? "80mm"}><option value="58mm">58mm</option><option value="80mm">80mm</option></select></label><label>طابعة الإيصال<input name="thermalPrinter" defaultValue={shop.thermalPrinterSettings?.printer ?? "default"} /></label><label>طابعة الملصق<input name="labelPrinter" defaultValue={shop.labelPrinterSettings?.printer ?? "default"} /></label><label>تذييل الإيصال<textarea name="receiptFooter" defaultValue={shop.receiptFooter ?? ""} /></label><h3>سير العمل والرسائل</h3><label className="check"><input name="readyRequiresApproval" type="checkbox" defaultChecked={shop.workflowSettings?.readyRequiresApproval !== "false"} /> يتطلب الإصلاح موافقة العميل</label><label>قالب رسالة الاستلام<textarea name="receivedTemplate" defaultValue={shop.messageTemplates?.received ?? "تم استلام جهازك في مركز الصيانة"} /></label><label>مزود واتساب<select name="whatsappMode" defaultValue={shop.whatsappSettings?.mode ?? "mock"}><option value="mock">تجريبي / Mock</option><option value="meta">Meta</option></select></label><button className="primary">حفظ الإعدادات</button></form>
    <section className="panel"><h2>الفروع</h2><form className="inline-form branch-form" onSubmit={addBranch}><input name="name" required placeholder="اسم الفرع" /><input name="code" required placeholder="الكود" /><input name="address" placeholder="العنوان" /><button className="primary">إضافة</button></form><div className="catalog-list">{branches.map((branch) => <article key={branch.id}><span><b>{branch.name}</b> · {branch.code}</span><button className="ghost" onClick={() => toggleBranch(branch)}>{branch.isActive ? "تعطيل" : "تفعيل"}</button></article>)}</div></section>
    <CatalogEditor title="ماركات الأجهزة" items={brands} kind="brands" add={add} patch={patchCatalog} rename={rename} /><CatalogEditor title="أنواع الأعطال" items={faults} kind="faults" add={add} patch={patchCatalog} rename={rename} />
    <section className="panel"><h2>واتساب</h2><p>قيد الانتظار: {outbox.filter((x) => x.status === "QUEUED").length} · تم الإرسال: {outbox.filter((x) => x.status === "SENT").length} · فشل: {outbox.filter((x) => x.status === "FAILED").length}</p><button className="primary" onClick={processOutbox}>معالجة قائمة الرسائل</button></section>
    <section className="panel"><h2>الاشتراك</h2>{subscription ? <><strong>{subscription.plan.name}</strong><p>{subscription.status} · {subscription.billingCycle}</p><small>بداية الاشتراك {new Date(subscription.startsAt).toLocaleDateString("ar-EG")}</small></> : <p>لا يوجد اشتراك مسجل</p>}</section>
  </section></>;
}

function CatalogEditor({ title, items, kind, add, patch, rename }: { title: string; items: CatalogItem[]; kind: "brands" | "faults"; add: (event: FormEvent<HTMLFormElement>, kind: "brands" | "faults") => void; patch: (kind: "brands" | "faults", item: CatalogItem, changes: Record<string, unknown>) => void; rename: (kind: "brands" | "faults", item: CatalogItem) => void }) {
  return <section className="panel"><h2>{title}</h2><form className="inline-form" onSubmit={(event) => add(event, kind)}><input name="name" required placeholder="اسم جديد" /><button className="primary">إضافة</button></form><div className="catalog-list">{items.map((item) => <article key={item.id}><span>{item.name}</span><div className="row"><button className="ghost" onClick={() => patch(kind, item, { sortOrder: Math.max(0, (item.sortOrder ?? 0) - 1) })}>↑</button><button className="ghost" onClick={() => patch(kind, item, { sortOrder: (item.sortOrder ?? 0) + 1 })}>↓</button><button className="ghost" onClick={() => rename(kind, item)}>تعديل</button><button className="ghost" onClick={() => patch(kind, item, { isActive: !item.isActive })}>{item.isActive ? "تعطيل" : "تفعيل"}</button></div></article>)}</div></section>;
}

