import { FormEvent, useEffect, useState } from "react";
import { api, downloadCsv } from "./api";
import type { Session } from "./auth";
import type { CatalogItem } from "./types";
import { PrinterWorkstationSettings } from "./PrinterSettings";

type Branch = { id: string; name: string; code: string; address?: string; phone?: string; isActive: boolean };
type Subscription = { status: string; billingCycle: string; startsAt: string; endsAt?: string; plan: { name: string; limits: Record<string, unknown> } } | null;

export function Settings({ session }: { session: Session }) {
  const [brands, setBrands] = useState<CatalogItem[]>([]); const [faults, setFaults] = useState<CatalogItem[]>([]); const [branches, setBranches] = useState<Branch[]>([]); const [shop, setShop] = useState<Record<string, any> | null>(null); const [subscription, setSubscription] = useState<Subscription>(null); const [message, setMessage] = useState(""); const [outbox, setOutbox] = useState<{ status: string; deliveredAt?: string; readAt?: string }[]>([]); const [whatsappStatus, setWhatsappStatus] = useState<{ status: string; provider: string; missing: string[]; webhookUrl: string } | null>(null);
  const load = () => Promise.all([api<CatalogItem[]>("/settings/brands", {}, session.token), api<CatalogItem[]>("/settings/faults", {}, session.token), api<Record<string, any>>("/settings/shop", {}, session.token), api<Branch[]>("/settings/branches", {}, session.token), api<Subscription>("/settings/subscription", {}, session.token), api<{ status: string; deliveredAt?: string; readAt?: string }[]>("/whatsapp/outbox", {}, session.token), api<{ status: string; provider: string; missing: string[]; webhookUrl: string }>("/settings/whatsapp/status", {}, session.token)]).then(([b, f, s, br, sub, messages, providerStatus]) => { setBrands(b); setFaults(f); setShop(s); setBranches(br); setSubscription(sub); setOutbox(messages); setWhatsappStatus(providerStatus); }).catch((e) => setMessage(e.message));
  useEffect(() => { void load(); }, [session.token]);
  async function add(event: FormEvent<HTMLFormElement>, kind: "brands" | "faults") { event.preventDefault(); const form = event.currentTarget; const d = new FormData(form); try { await api(`/settings/${kind}`, { method: "POST", body: JSON.stringify({ name: d.get("name"), sortOrder: 0, isActive: true }) }, session.token); form.reset(); setMessage("تمت الإضافة"); load(); } catch (e) { setMessage((e as Error).message); } }
  async function patchCatalog(kind: "brands" | "faults", item: CatalogItem, changes: Record<string, unknown>) { try { await api(`/settings/${kind}/${item.id}`, { method: "PATCH", body: JSON.stringify(changes) }, session.token); load(); } catch (e) { setMessage((e as Error).message); } }
  async function rename(kind: "brands" | "faults", item: CatalogItem) { const name = window.prompt("الاسم الجديد", item.name); if (name?.trim() && name !== item.name) await patchCatalog(kind, item, { name: name.trim() }); }
  async function saveShop(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const d = new FormData(event.currentTarget); const body = { name: d.get("name"), phone: d.get("phone") || null, whatsapp: d.get("whatsapp") || null, address: d.get("address") || null, logoUrl: d.get("logoUrl") || null, primaryColor: d.get("primaryColor"), receiptFooter: d.get("receiptFooter") || null, receiptPaperWidth: d.get("receiptPaperWidth"), thermalPrinterSettings: { printer: String(d.get("thermalPrinter") || "default") }, labelPrinterSettings: { printer: String(d.get("labelPrinter") || "default") }, whatsappSettings: { mode: String(d.get("whatsappMode") || "mock") }, workflowSettings: { readyRequiresApproval: String(d.get("readyRequiresApproval") === "on") }, messageTemplates: { received: String(d.get("receivedTemplate") || "") } }; try { await api("/settings/shop", { method: "PATCH", body: JSON.stringify(body) }, session.token); setMessage("تم حفظ إعدادات المركز"); load(); } catch (e) { setMessage((e as Error).message); } }
  async function addBranch(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const d = Object.fromEntries(new FormData(form)); try { await api("/settings/branches", { method: "POST", body: JSON.stringify(d) }, session.token); form.reset(); load(); } catch (e) { setMessage((e as Error).message); } }
  async function toggleBranch(branch: Branch) { try { await api(`/settings/branches/${branch.id}`, { method: "PATCH", body: JSON.stringify({ isActive: !branch.isActive }) }, session.token); load(); } catch (e) { setMessage((e as Error).message); } }
  async function processOutbox() { try { const result = await api<{ processed: number; sent: number; failed: number }>("/whatsapp/process", { method: "POST" }, session.token); setMessage(`تمت معالجة ${result.processed} رسالة: ${result.sent} ناجحة، ${result.failed} فاشلة`); load(); } catch (e) { setMessage((e as Error).message); } }
  async function testWhatsappConfig() { try { await api("/settings/whatsapp/test-config", { method: "POST" }, session.token); setMessage("تم التحقق من اتصال Meta بنجاح"); load(); } catch (e) { setMessage((e as Error).message); } }
  async function resendWhatsapp(id: string) { try { await api(`/whatsapp/${id}/resend`, { method: "POST" }, session.token); setMessage("تمت إعادة الرسالة إلى قائمة الإرسال"); load(); } catch (e) { setMessage((e as Error).message); } }
  async function sendTestMessage(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); try { await api("/settings/whatsapp/test-message", { method: "POST", body: JSON.stringify({ recipient: data.get("recipient"), templateKey: data.get("templateKey") }) }, session.token); setMessage("تم قبول رسالة الاختبار من Meta"); } catch (e) { setMessage((e as Error).message); } }
  async function exportData(kind: "customers" | "repairs" | "payments" | "expenses") { try { const blob = await downloadCsv(`/exports/${kind}.csv`, session.token); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${kind}-${new Date().toISOString().slice(0,10)}.csv`; link.click(); URL.revokeObjectURL(url); setMessage("تم تجهيز ملف التصدير"); } catch (e) { setMessage((e as Error).message); } }  if (!shop) return <div className="loading">جارٍ تحميل الإعدادات…</div>;
  return <><header><div><span className="eyebrow">إدارة النظام</span><h1>إعدادات المركز</h1></div></header>{message && <div className={message.startsWith("تم") ? "success" : "error"}>{message}</div>}<section className="settings-grid">
    <form className="panel" onSubmit={saveShop}><h2>عام وهوية المركز</h2><label>اسم المحل<input name="name" defaultValue={shop.name} required /></label><label>اللوجو (URL)<input name="logoUrl" type="url" defaultValue={shop.logoUrl ?? ""} /></label><label>الهاتف<input name="phone" defaultValue={shop.phone ?? ""} /></label><label>واتساب<input name="whatsapp" defaultValue={shop.whatsapp ?? ""} /></label><label>العنوان<input name="address" defaultValue={shop.address ?? ""} /></label><label>اللون الرئيسي<input name="primaryColor" type="color" defaultValue={shop.primaryColor ?? "#0f766e"} /></label><h3>إيصال الاستلام والطابعات</h3><label>مقاس الورق<select name="receiptPaperWidth" defaultValue={shop.receiptPaperWidth ?? "80mm"}><option value="58mm">58mm</option><option value="80mm">80mm</option></select></label><label>طابعة الإيصال<input name="thermalPrinter" defaultValue={shop.thermalPrinterSettings?.printer ?? "default"} /></label><label>طابعة الملصق<input name="labelPrinter" defaultValue={shop.labelPrinterSettings?.printer ?? "default"} /></label><label>تذييل الإيصال<textarea name="receiptFooter" defaultValue={shop.receiptFooter ?? ""} /></label><h3>سير العمل والرسائل</h3><label className="check"><input name="readyRequiresApproval" type="checkbox" defaultChecked={shop.workflowSettings?.readyRequiresApproval !== "false"} /> يتطلب الإصلاح موافقة العميل</label><label>قالب رسالة الاستلام<textarea name="receivedTemplate" defaultValue={shop.messageTemplates?.received ?? "تم استلام جهازك في مركز الصيانة"} /></label><label>مزود واتساب<select name="whatsappMode" defaultValue={shop.whatsappSettings?.mode ?? "mock"}><option value="mock">تجريبي / Mock</option><option value="meta">Meta</option></select></label><button className="primary">حفظ الإعدادات</button></form>
    <section className="panel"><h2>الفروع</h2><form className="inline-form branch-form" onSubmit={addBranch}><input name="name" required placeholder="اسم الفرع" /><input name="code" required placeholder="الكود" /><input name="address" placeholder="العنوان" /><button className="primary">إضافة</button></form><div className="catalog-list">{branches.map((branch) => <article key={branch.id}><span><b>{branch.name}</b> · {branch.code}</span><button className="ghost" onClick={() => toggleBranch(branch)}>{branch.isActive ? "تعطيل" : "تفعيل"}</button></article>)}</div></section>
    <CatalogEditor title="ماركات الأجهزة" items={brands} kind="brands" add={add} patch={patchCatalog} rename={rename} /><CatalogEditor title="أنواع الأعطال" items={faults} kind="faults" add={add} patch={patchCatalog} rename={rename} />
    <section className="panel"><h2>واتساب</h2><p><b>الحالة: {whatsappStatus?.status === "META_CONNECTED" ? "Meta متصل" : whatsappStatus?.status === "META_READY" ? "Meta جاهز للاختبار" : whatsappStatus?.status === "TEST" ? "تجريبي" : whatsappStatus?.status === "ERROR" ? "الإعداد غير مكتمل" : "غير مهيأ"}</b></p>{Boolean(whatsappStatus?.missing.length) && <p className="hint">الإعدادات الناقصة: {whatsappStatus?.missing.join("، ")}</p>}<label>Webhook URL<input readOnly dir="ltr" value={whatsappStatus?.webhookUrl ?? ""} onFocus={(e) => e.currentTarget.select()} /></label><div className="row wrap"><button type="button" className="ghost" onClick={() => navigator.clipboard.writeText(whatsappStatus?.webhookUrl ?? "")}>نسخ رابط Webhook</button><button type="button" className="ghost" onClick={testWhatsappConfig}>اختبار إعداد Meta</button><button type="button" className="primary" onClick={processOutbox}>معالجة قائمة الرسائل</button></div><form className="compact-form" onSubmit={sendTestMessage}><h3>رسالة اختبار حقيقية</h3><input name="recipient" dir="ltr" required placeholder="201xxxxxxxxx" /><input name="templateKey" dir="ltr" required defaultValue="hello_world" placeholder="اسم القالب المعتمد" /><button className="ghost">إرسال عبر Meta</button></form><p>في الانتظار: {outbox.filter((x) => x.status === "QUEUED").length} · أُرسلت: {outbox.filter((x) => x.status === "SENT" && !x.deliveredAt).length} · سُلّمت: {outbox.filter((x) => Boolean(x.deliveredAt) && !x.readAt).length} · قُرئت: {outbox.filter((x) => Boolean(x.readAt)).length} · فشلت: {outbox.filter((x) => x.status === "FAILED").length}</p><div className="catalog-list">{outbox.slice(0, 20).map((item: any) => <article key={item.id}><span><b>{item.type}</b> · <span dir="ltr">{item.recipient}</span> · {item.status}{item.failureReason ? ` · ${item.failureReason}` : ""}</span>{item.status === "FAILED" && <button type="button" className="ghost" onClick={() => resendWhatsapp(item.id)}>إعادة المحاولة</button>}</article>)}</div></section>
    <section className="panel"><h2>تصدير البيانات</h2><p className="hint">ملفات CSV معزولة حسب المركز والفرع وصلاحيات المستخدم.</p><div className="row wrap"><button type="button" className="ghost" onClick={() => exportData("customers")}>العملاء</button><button type="button" className="ghost" onClick={() => exportData("repairs")}>أوامر الصيانة</button>{session.user.permissions.includes("report.financial.view") && <><button type="button" className="ghost" onClick={() => exportData("payments")}>المدفوعات</button><button type="button" className="ghost" onClick={() => exportData("expenses")}>المصروفات</button></>}</div></section>
    <section className="panel"><h2>الاشتراك</h2>{subscription ? <><strong>{subscription.plan.name}</strong><p>{subscription.status} · {subscription.billingCycle}</p><small>بداية الاشتراك {new Date(subscription.startsAt).toLocaleDateString("ar-EG")}</small></> : <p>لا يوجد اشتراك مسجل</p>}</section>
    <PrinterWorkstationSettings session={session} />
  </section></>;
}

function CatalogEditor({ title, items, kind, add, patch, rename }: { title: string; items: CatalogItem[]; kind: "brands" | "faults"; add: (event: FormEvent<HTMLFormElement>, kind: "brands" | "faults") => void; patch: (kind: "brands" | "faults", item: CatalogItem, changes: Record<string, unknown>) => void; rename: (kind: "brands" | "faults", item: CatalogItem) => void }) {
  return <section className="panel"><h2>{title}</h2><form className="inline-form" onSubmit={(event) => add(event, kind)}><input name="name" required placeholder="اسم جديد" /><button className="primary">إضافة</button></form><div className="catalog-list">{items.map((item) => <article key={item.id}><span>{item.name}</span><div className="row"><button className="ghost" onClick={() => patch(kind, item, { sortOrder: Math.max(0, (item.sortOrder ?? 0) - 1) })}>↑</button><button className="ghost" onClick={() => patch(kind, item, { sortOrder: (item.sortOrder ?? 0) + 1 })}>↓</button><button className="ghost" onClick={() => rename(kind, item)}>تعديل</button><button className="ghost" onClick={() => patch(kind, item, { isActive: !item.isActive })}>{item.isActive ? "تعطيل" : "تفعيل"}</button></div></article>)}</div></section>;
}
