import { useMemo, useRef, useState, type ChangeEvent, type FormEvent } from "react";
import { api } from "./api";

type BranchDraft = { name: string; code: string; address: string; phone: string; whatsapp: string; workstationName: string; workstationType: "RECEPTION" | "WORKSHOP" | "CASHIER" | "MANAGER"; workstationCount: number };
type SetupResult = { success: true; centerCode: string; identity: string; email: string };
export type SetupPrefill = { tenant: string; identity: string };

export function SetupWizard({ onComplete, onCancel }: { onComplete: (value: SetupPrefill) => void; onCancel: () => void }) {
  const [step, setStep] = useState(1); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const key = useRef(crypto.randomUUID());
  const [owner, setOwner] = useState({ fullName: "", username: "", email: "", phone: "", whatsapp: "", password: "", confirm: "" });
  const [shop, setShop] = useState({ name: "", code: "", phone: "", whatsapp: "", address: "", governorate: "", city: "", notes: "", logoDataUrl: "" });
  const [branches, setBranches] = useState<BranchDraft[]>([{ name: "الفرع الرئيسي", code: "MAIN", address: "", phone: "", whatsapp: "", workstationName: "الاستقبال", workstationType: "RECEPTION", workstationCount: 1 }]);
  const [defaults, setDefaults] = useState({ currency: "EGP", timezone: "Africa/Cairo", paperWidth: "80mm", warrantyDays: 30, whatsappMode: "later" }); const [subscription, setSubscription] = useState({ planCode: "STARTER", billingCycle: "TRIAL" }); const [accepted, setAccepted] = useState(false);
  const payload = useMemo(() => ({ owner: { fullName: owner.fullName, username: owner.username, email: owner.email, phone: owner.phone, whatsapp: owner.whatsapp, password: owner.password }, shop, branches: branches.map((b) => ({ name: b.name, code: b.code, address: b.address || undefined, phone: b.phone || undefined, whatsapp: b.whatsapp || undefined, workstations: [{ name: b.workstationName, type: b.workstationType, count: b.workstationCount, defaultPage: b.workstationType === "WORKSHOP" ? "workshop" : b.workstationType === "CASHIER" ? "finance" : "dashboard" }] })), defaults, subscription, acceptedTerms: accepted }), [owner, shop, branches, defaults, subscription, accepted]);
  function updateBranch(index: number, changes: Partial<BranchDraft>) { setBranches((items) => items.map((item, i) => i === index ? { ...item, ...changes } : item)); }
  async function logo(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (![/^image\/png$/, /^image\/jpeg$/, /^image\/webp$/].some((x) => x.test(file.type)) || file.size > 256_000) { setError("استخدم شعار PNG أو JPEG أو WebP بحجم لا يتجاوز 250 كيلوبايت"); return; } const reader = new FileReader(); reader.onload = () => setShop((x) => ({ ...x, logoDataUrl: String(reader.result) })); reader.readAsDataURL(file); }
  function next(event: FormEvent) { event.preventDefault(); setError(""); if (step === 1 && owner.password !== owner.confirm) return setError("تأكيد كلمة المرور غير مطابق"); if (step === 2 && !shop.code.match(/^[a-z0-9-]{3,40}$/)) return setError("رمز المركز يقبل حروفًا إنجليزية صغيرة وأرقامًا وشرطة فقط"); setStep((x) => Math.min(7, x + 1)); }
  async function finish() { if (!accepted || busy) return; setBusy(true); setError(""); try { const result = await api<SetupResult>("/public/setup", { method: "POST", headers: { "idempotency-key": key.current }, body: JSON.stringify(payload) }); onComplete({ tenant: result.centerCode, identity: result.identity }); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <div className="setup-shell" dir="rtl"><section className="setup-card"><div className="row between"><div><span className="eyebrow">إعداد مركز جديد</span><h1>الخطوة {step} من 7</h1></div><button className="ghost" onClick={onCancel}>لدي حساب</button></div><div className="setup-progress"><i style={{ width: `${step / 7 * 100}%` }} /></div>
    {step === 1 && <form className="grid" onSubmit={next}><h2 className="wide">بيانات مالك المركز</h2><label>الاسم بالكامل<input required minLength={3} value={owner.fullName} onChange={(e) => setOwner({ ...owner, fullName: e.target.value })} /></label><label>اسم المستخدم<input required pattern="[a-z0-9._-]{3,40}" dir="ltr" value={owner.username} onChange={(e) => setOwner({ ...owner, username: e.target.value.toLowerCase() })} /></label><label>البريد الإلكتروني<input required type="email" dir="ltr" value={owner.email} onChange={(e) => setOwner({ ...owner, email: e.target.value })} /></label><label>الهاتف<input required value={owner.phone} onChange={(e) => setOwner({ ...owner, phone: e.target.value })} /></label><label>واتساب<input required value={owner.whatsapp} onChange={(e) => setOwner({ ...owner, whatsapp: e.target.value })} /></label><label>كلمة المرور<input required type="password" minLength={10} value={owner.password} onChange={(e) => setOwner({ ...owner, password: e.target.value })} /></label><label>تأكيد كلمة المرور<input required type="password" minLength={10} value={owner.confirm} onChange={(e) => setOwner({ ...owner, confirm: e.target.value })} /></label><button className="primary wide">التالي</button></form>}
    {step === 2 && <form className="grid" onSubmit={next}><h2 className="wide">بيانات المركز</h2><label>اسم المركز<input required value={shop.name} onChange={(e) => setShop({ ...shop, name: e.target.value, code: shop.code || e.target.value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") })} /></label><label>رمز المركز<input required dir="ltr" value={shop.code} onChange={(e) => setShop({ ...shop, code: e.target.value.toLowerCase() })} /><small>يمكن تعديله ويجب أن يكون فريدًا</small></label><label>الهاتف<input required value={shop.phone} onChange={(e) => setShop({ ...shop, phone: e.target.value })} /></label><label>واتساب<input required value={shop.whatsapp} onChange={(e) => setShop({ ...shop, whatsapp: e.target.value })} /></label><label>المحافظة<input required value={shop.governorate} onChange={(e) => setShop({ ...shop, governorate: e.target.value })} /></label><label>المدينة<input required value={shop.city} onChange={(e) => setShop({ ...shop, city: e.target.value })} /></label><label className="wide">العنوان<input required value={shop.address} onChange={(e) => setShop({ ...shop, address: e.target.value })} /></label><label>شعار المركز<input type="file" accept="image/png,image/jpeg,image/webp" onChange={logo} /></label><label>ملاحظات<input value={shop.notes} onChange={(e) => setShop({ ...shop, notes: e.target.value })} /></label><button className="primary wide">التالي</button></form>}
    {step === 3 && <form onSubmit={next}><h2>الفروع</h2>{branches.map((b, i) => <div className="grid setup-row" key={i}><label>اسم الفرع<input required value={b.name} onChange={(e) => updateBranch(i, { name: e.target.value })} /></label><label>الكود<input required value={b.code} onChange={(e) => updateBranch(i, { code: e.target.value.toUpperCase() })} /></label><label>العنوان<input value={b.address} onChange={(e) => updateBranch(i, { address: e.target.value })} /></label><label>الهاتف<input value={b.phone} onChange={(e) => updateBranch(i, { phone: e.target.value })} /></label>{branches.length > 1 && <button type="button" className="ghost" onClick={() => setBranches((x) => x.filter((_, n) => n !== i))}>حذف الفرع</button>}</div>)}<button type="button" className="ghost" onClick={() => setBranches((x) => [...x, { name: "", code: `B${x.length + 1}`, address: "", phone: "", whatsapp: "", workstationName: "الاستقبال", workstationType: "RECEPTION", workstationCount: 1 }])}>إضافة فرع</button><button className="primary">التالي</button></form>}
    {step === 4 && <form onSubmit={next}><h2>محطات العمل لكل فرع</h2>{branches.map((b, i) => <div className="grid setup-row" key={i}><strong className="wide">{b.name}</strong><label>اسم المحطة<input required value={b.workstationName} onChange={(e) => updateBranch(i, { workstationName: e.target.value })} /></label><label>النوع<select value={b.workstationType} onChange={(e) => updateBranch(i, { workstationType: e.target.value as BranchDraft["workstationType"] })}><option value="RECEPTION">استقبال</option><option value="WORKSHOP">ورشة</option><option value="CASHIER">خزينة</option><option value="MANAGER">إدارة</option></select></label><label>العدد<input type="number" min={1} max={20} value={b.workstationCount} onChange={(e) => updateBranch(i, { workstationCount: Number(e.target.value) })} /></label></div>)}<button className="primary">التالي</button></form>}
    {step === 5 && <form className="grid" onSubmit={next}><h2 className="wide">الإعدادات الافتراضية</h2><label>العملة<select value={defaults.currency} onChange={(e) => setDefaults({ ...defaults, currency: e.target.value })}><option>EGP</option><option>SAR</option><option>AED</option><option>USD</option></select></label><label>المنطقة الزمنية<input value={defaults.timezone} onChange={(e) => setDefaults({ ...defaults, timezone: e.target.value })} /></label><label>مقاس الإيصال<select value={defaults.paperWidth} onChange={(e) => setDefaults({ ...defaults, paperWidth: e.target.value })}><option>80mm</option><option>58mm</option></select></label><label>الضمان الافتراضي بالأيام<input type="number" min={0} max={730} value={defaults.warrantyDays} onChange={(e) => setDefaults({ ...defaults, warrantyDays: Number(e.target.value) })} /></label><label>واتساب<select value={defaults.whatsappMode} onChange={(e) => setDefaults({ ...defaults, whatsappMode: e.target.value })}><option value="later">إعداده لاحقًا</option><option value="meta">Meta لاحقًا</option></select></label><button className="primary wide">التالي</button></form>}
    {step === 6 && <form className="grid" onSubmit={next}><h2 className="wide">الخطة والاشتراك</h2><label>الخطة<select value={subscription.planCode} onChange={(e) => setSubscription({ ...subscription, planCode: e.target.value })}><option value="STARTER">Starter</option></select></label><label>الدورة<select value={subscription.billingCycle} onChange={(e) => setSubscription({ ...subscription, billingCycle: e.target.value })}><option value="TRIAL">تجربة 14 يومًا</option><option value="MONTHLY">شهري (تفعيل يدوي)</option><option value="YEARLY">سنوي (تفعيل يدوي)</option></select></label><p className="hint wide">لا يتم تحصيل أي دفع إلكتروني. يبدأ المركز بفترة تجربة ويسجل اختيارك للمراجعة اليدوية.</p><button className="primary wide">مراجعة البيانات</button></form>}
    {step === 7 && <section><h2>المراجعة النهائية</h2><dl className="setup-review"><div><dt>بيانات صاحب المركز</dt><dd>{owner.fullName} · @{owner.username} · {owner.email}<br />كلمة المرور: ••••••••••</dd><button className="ghost" onClick={() => setStep(1)}>تعديل</button></div><div><dt>بيانات مركز الصيانة ورمز المركز</dt><dd>{shop.name} · {shop.code}</dd><button className="ghost" onClick={() => setStep(2)}>تعديل</button></div><div><dt>الفروع</dt><dd>{branches.map((x) => x.name).join("، ")}</dd><button className="ghost" onClick={() => setStep(3)}>تعديل</button></div><div><dt>أجهزة التشغيل</dt><dd>{branches.map((x) => `${x.name} (${x.workstationCount} محطة)`).join("، ")}</dd><button className="ghost" onClick={() => setStep(4)}>تعديل</button></div><div><dt>الإعدادات الافتراضية</dt><dd>{defaults.currency} · {defaults.timezone} · {defaults.paperWidth}</dd><button className="ghost" onClick={() => setStep(5)}>تعديل</button></div><div><dt>الخطة / الاشتراك</dt><dd>{subscription.planCode} · {subscription.billingCycle}</dd><button className="ghost" onClick={() => setStep(6)}>تعديل</button></div></dl><label className="check"><input type="checkbox" checked={accepted} onChange={(e) => setAccepted(e.target.checked)} /> أؤكد صحة البيانات وأوافق على إنشاء المركز</label><button className="primary" disabled={!accepted || busy} onClick={finish}>{busy ? "جارٍ إنشاء المركز…" : "إنشاء المركز"}</button></section>}
    {error && <div className="error">{error}</div>}{step > 1 && <button className="ghost setup-back" disabled={busy} onClick={() => setStep((x) => x - 1)}>السابق</button>}
  </section></div>;
}

