import { FormEvent, useEffect, useState } from "react";
import { api } from "./api";
import type { Session } from "./auth";
import type { Catalog } from "./types";

type Permission = { id: string; description: string };
type Role = { id: string; name: string; permissions?: { permissionId: string }[] };
type User = { id: string; name: string; email: string; branchId?: string; isActive: boolean; roles: { role: Role }[] };

export function Users({ session }: { session: Session }) {
  const canManageRoles = session.user.permissions.includes("role.manage"); const [users, setUsers] = useState<User[]>([]); const [roles, setRoles] = useState<Role[]>([]); const [permissions, setPermissions] = useState<Permission[]>([]); const [branches, setBranches] = useState<Catalog["branches"]>([]); const [message, setMessage] = useState("");
  const load = () => Promise.all([api<User[]>("/settings/users", {}, session.token), api<Role[]>("/settings/roles", {}, session.token), api<Catalog>("/catalog", {}, session.token), canManageRoles ? api<Permission[]>("/settings/permissions", {}, session.token) : Promise.resolve([])]).then(([u, r, c, p]) => { setUsers(u); setRoles(r); setBranches(c.branches); setPermissions(p); }).catch((e) => setMessage(e.message));
  useEffect(() => { void load(); }, [session.token]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const d = new FormData(form); try { await api("/settings/users", { method: "POST", body: JSON.stringify({ name: d.get("name"), email: d.get("email"), password: d.get("password"), branchId: d.get("branchId") || null, roleIds: [d.get("roleId")] }) }, session.token); form.reset(); setMessage("تم إنشاء المستخدم"); load(); } catch (e) { setMessage((e as Error).message); } }
  async function toggle(user: User) { try { await api(`/settings/users/${user.id}`, { method: "PATCH", body: JSON.stringify({ isActive: !user.isActive }) }, session.token); load(); } catch (e) { setMessage((e as Error).message); } }
  async function saveRole(event: FormEvent<HTMLFormElement>, role: Role) { event.preventDefault(); const d = new FormData(event.currentTarget); try { await api(`/settings/roles/${role.id}`, { method: "PATCH", body: JSON.stringify({ permissionIds: d.getAll("permissions") }) }, session.token); setMessage(`تم حفظ صلاحيات ${role.name}`); load(); } catch (e) { setMessage((e as Error).message); } }
  return <><header><div><span className="eyebrow">التحكم في الوصول</span><h1>المستخدمون والأدوار</h1></div></header>{message && <div className={message.startsWith("تم") ? "success" : "error"}>{message}</div>}<section className="panel"><h2>إضافة مستخدم</h2><form className="grid" onSubmit={create}><label>الاسم<input name="name" required /></label><label>البريد الإلكتروني<input name="email" type="email" required /></label><label>كلمة مرور مؤقتة<input name="password" type="password" minLength={8} required /></label><label>الفرع<select name="branchId"><option value="">كل الفروع</option>{branches.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>الدور<select name="roleId" required>{roles.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button className="primary">إنشاء المستخدم</button></form></section><section className="panel"><h2>المستخدمون الحاليون</h2><div className="table">{users.map((user) => <article key={user.id}><div><b>{user.name}</b><small>{user.email}</small></div><span>{user.roles.map((x) => x.role.name).join("، ")}</span><em>{user.isActive ? "نشط" : "معطل"}</em><button className="ghost" onClick={() => toggle(user)}>{user.isActive ? "تعطيل" : "تفعيل"}</button></article>)}</div></section>{canManageRoles && <section className="panel"><h2>الأدوار والصلاحيات</h2><div className="roles-grid">{roles.map((role) => <form key={role.id} onSubmit={(event) => saveRole(event, role)}><h3>{role.name}</h3><div className="permission-list">{permissions.map((permission) => <label key={permission.id}><input type="checkbox" name="permissions" value={permission.id} defaultChecked={role.permissions?.some((item) => item.permissionId === permission.id)} /> {permission.id}</label>)}</div><button className="primary">حفظ صلاحيات الدور</button></form>)}</div></section>}</>;
}

