import { FormEvent, useEffect, useState } from "react";
import { statusLabels, type RepairStatus } from "@repair/domain";
import { api } from "./api";
import type { Session } from "./auth";
import type { Repair } from "./types";
import { formatMoney } from "./types";
import { useRepairEvents } from "./useRepairEvents";

export const workshopColumns: RepairStatus[] = ["RECEIVED", "DIAGNOSING", "AWAITING_CUSTOMER_APPROVAL", "CUSTOMER_APPROVED", "CUSTOMER_DECLINED", "UNDER_REPAIR", "READY_FOR_DELIVERY", "READY_FOR_RETURN_WITHOUT_REPAIR", "DELIVERED"];
const nextAction: Partial<Record<RepairStatus, { status: RepairStatus; label: string }>> = { RECEIVED: { status: "DIAGNOSING", label: "بدء الفحص" }, CUSTOMER_APPROVED: { status: "UNDER_REPAIR", label: "بدء الصيانة" }, CUSTOMER_DECLINED: { status: "READY_FOR_RETURN_WITHOUT_REPAIR", label: "جاهز للعودة بدون إصلاح" }, UNDER_REPAIR: { status: "READY_FOR_DELIVERY", label: "جاهز للتسليم" } };
const printStatusLabel: Record<string, string> = { QUEUED: "في انتظار الطباعة", PROCESSING: "جارٍ الطباعة", COMPLETED: "تمت الطباعة", FAILED: "فشلت الطباعة" };
const whatsappStatusLabel = (message: Repair["whatsappMessages"][number]) => message.readAt ? "تمت القراءة" : message.deliveredAt ? "تم التسليم" : message.status === "SENT" ? "تم الإرسال" : message.status === "FAILED" ? "فشل الإرسال" : "في انتظار الإرسال";

export function Workshop({ session }: { session: Session }) {
  const eventRevision = useRepairEvents(session, ["repair.created", "repair.status.changed", "quote.created", "quote.decided", "repair.delivered"]);
  const [repairs, setRepairs] = useState<Repair[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null); const [detail, setDetail] = useState<Repair | null>(null); const [technicians, setTechnicians] = useState<{ id: string; name: string }[]>([]); const [message, setMessage] = useState("");
  const load = () => api<Repair[]>("/repairs", {}, session.token).then(setRepairs).catch((e) => setMessage(e.message));
  const loadDetail = (id: string) => api<Repair>(`/repairs/${id}`, {}, session.token).then(setDetail).catch((e) => setMessage(e.message));
  useEffect(() => { void load(); if (selectedId) void loadDetail(selectedId); }, [session.token, eventRevision]);
  useEffect(() => { api<{ id: string; name: string }[]>("/workshop/technicians", {}, session.token).then(setTechnicians).catch(() => undefined); }, [session.token]);
  useEffect(() => { if (selectedId) void loadDetail(selectedId); else setDetail(null); }, [selectedId]);
  async function status(value: RepairStatus) { if (!detail) return; try { const result = await api<{ message?: string }>(`/repairs/${detail.id}/status`, { method: "POST", body: JSON.stringify({ status: value }) }, session.token); setMessage(result.message ?? "تم تحديث الحالة"); await Promise.all([load(), loadDetail(detail.id)]); } catch (e) { setMessage((e as Error).message); } }
  async function note(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!detail) return; const form = event.currentTarget; const d = new FormData(form); try { await api(`/repairs/${detail.id}/notes`, { method: "POST", body: JSON.stringify({ type: d.get("type"), body: d.get("body") }) }, session.token); form.reset(); await loadDetail(detail.id); setMessage("تم حفظ الملاحظة"); } catch (e) { setMessage((e as Error).message); } }
  async function quote(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!detail) return; const form = event.currentTarget; const d = new FormData(form); try { const result = await api<{ message?: string }>(`/repairs/${detail.id}/quotes`, { method: "POST", body: JSON.stringify({ amount: d.get("amount"), diagnosis: d.get("diagnosis"), customerNote: d.get("customerNote") || undefined }) }, session.token); setMessage(result.message ?? "تم إنشاء عرض السعر"); form.reset(); await Promise.all([load(), loadDetail(detail.id)]); } catch (e) { setMessage((e as Error).message); } }
  async function assign(technicianId: string) { if (!detail || !technicianId) return; try { await api(`/repairs/${detail.id}/assign`, { method: "POST", body: JSON.stringify({ technicianId }) }, session.token); await loadDetail(detail.id); setMessage("تم إسناد أمر الصيانة"); } catch (e) { setMessage((e as Error).message); } }
  async function reprint(jobId: string) { if (!detail) return; try { await api(`/print-jobs/${jobId}/reprint`, { method: "POST" }, session.token); setMessage("تمت إضافة نسخة جديدة إلى طابور الطباعة"); await loadDetail(detail.id); } catch (e) { setMessage((e as Error).message); } }
  async function resendWhatsapp(messageId?: string) { if (!detail) return; try { const result = await api<{ status: string }>(`/repairs/${detail.id}/whatsapp/resend`, { method: "POST", body: JSON.stringify(messageId ? { messageId } : {}) }, session.token); setMessage(result.status === "SENT" ? "تمت إعادة إرسال رسالة واتساب" : "تمت إضافة الرسالة إلى قائمة الإرسال"); await loadDetail(detail.id); } catch (e) { setMessage((e as Error).message); } }
  async function reveal() { if (!detail) return; try { const result = await api<{ value: string | null }>(`/repairs/${detail.id}/unlock/reveal`, { method: "POST" }, session.token); window.alert(result.value ? `بيانات الفتح: ${result.value}` : "لا توجد بيانات فتح مسجلة"); } catch (e) { setMessage((e as Error).message); } }
  async function correct(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!detail) return; const form = event.currentTarget; const d = new FormData(form); try { await api(`/repairs/${detail.id}/status/correct`, { method: "POST", body: JSON.stringify({ status: d.get("status"), reason: d.get("reason") }) }, session.token); form.reset(); setMessage("تم تصحيح الحالة مع الاحتفاظ بالسجل"); await Promise.all([load(), loadDetail(detail.id)]); } catch (e) { setMessage((e as Error).message); } }
  return <>
    <header><div><span className="eyebrow">الدور العلوي · الورشة</span><h1>مسار الصيانة</h1></div></header>
    {message && <div className={message.startsWith("تم") ? "success" : "error"}>{message}</div>}
    <div className="kanban" data-testid="workshop-board">{workshopColumns.map((statusValue) => { const items = repairs.filter((repair) => repair.status === statusValue); return <section key={statusValue}><h3>{statusLabels[statusValue]} <small>{items.length}</small></h3>{items.map((repair) => <article key={repair.id} className="clickable" onClick={() => setSelectedId(repair.id)}><b>{repair.repairNumber}</b><strong>{repair.brand.name} {repair.model}</strong><span>{repair.customer.name}</span><small dir="ltr">{repair.customer.phoneDisplay}</small></article>)}{!items.length && <div className="empty">لا توجد أجهزة</div>}</section>; })}</div>
    {detail && <div className="drawer workshop-drawer"><button className="close" onClick={() => setSelectedId(null)}>×</button><span className="eyebrow">{detail.repairNumber}</span><h2>{detail.brand.name} {detail.model}</h2><div className="customer-contact"><div><b>{detail.customer.name}</b><span dir="ltr">{detail.customer.phoneDisplay}</span></div>{detail.customer.whatsappPhone && <a className="whatsapp-link" href={`https://wa.me/${detail.customer.whatsappPhone.replace(/\D/g, "")}`} target="_blank" rel="noreferrer">فتح واتساب</a>}</div><span className="status-badge">{statusLabels[detail.status]}</span>
      <dl><div><dt>وصف العطل</dt><dd>{detail.reportedFault}</dd></div><div><dt>الأعطال المحددة</dt><dd>{detail.faults.map((item) => item.faultPreset.name).join("، ") || "لا توجد"}</dd></div><div><dt>السعر الحالي</dt><dd>{formatMoney(detail.finalCharge)}</dd></div><div><dt>المتبقي</dt><dd>{formatMoney(detail.remaining)}</dd></div></dl>
      <div className="row wrap"><select aria-label="إسناد لفني" defaultValue="" onChange={(e) => assign(e.target.value)}><option value="">إسناد لفني…</option>{technicians.map((x) => <option value={x.id} key={x.id}>{x.name}</option>)}</select>{session.user.permissions.includes("repair.unlock.view") && <button className="ghost" onClick={reveal}>عرض بيانات الفتح</button>}{nextAction[detail.status] && <button className="primary" onClick={() => status(nextAction[detail.status]!.status)}>{nextAction[detail.status]!.label}</button>}</div>
      {session.user.permissions.includes("repair.status.correct") && <form className="compact-form" onSubmit={correct}><h3>تصحيح الحالة إداريًا</h3><select name="status" required>{workshopColumns.concat(["CANCELLED"]).map((value) => <option key={value} value={value}>{statusLabels[value]}</option>)}</select><input name="reason" minLength={5} required placeholder="سبب التصحيح (إجباري)" /><button className="ghost">تسجيل التصحيح</button></form>}
      <form className="compact-form" onSubmit={note}><h3>إضافة ملاحظة</h3><select name="type"><option value="DIAGNOSTIC">تشخيص</option><option value="INTERNAL">داخلية</option></select><textarea name="body" required placeholder="تفاصيل التشخيص أو الملاحظة" /><button className="ghost">حفظ الملاحظة</button></form>
      {session.user.permissions.includes("repair.quote.create") && !["DELIVERED", "CANCELLED", "READY_FOR_DELIVERY", "READY_FOR_RETURN_WITHOUT_REPAIR"].includes(detail.status) && <form className="compact-form" onSubmit={quote}><h3>عرض سعر للعميل</h3><input name="amount" type="number" min="0" step="0.01" required placeholder="المبلغ" /><textarea name="diagnosis" required placeholder="التشخيص" /><input name="customerNote" placeholder="ملاحظة تظهر للعميل" /><button className="primary">إرسال للموافقة</button></form>}
      {session.user.permissions.includes("whatsapp.manage") && <section className="history whatsapp-history"><div className="row between"><h3>رسائل العميل</h3><button className="ghost" disabled={!detail.whatsappMessages.length} onClick={() => resendWhatsapp()}>إعادة إرسال آخر رسالة</button></div>{!detail.whatsappMessages.length && <p className="hint">لا توجد رسالة محفوظة لهذا الأمر بعد.</p>}{detail.whatsappMessages.map((item) => <article key={item.id}><div><b>{item.type.replaceAll("_", " ")}</b><small>{new Date(item.createdAt).toLocaleString("ar-EG")}</small></div><span className={`message-state ${item.status.toLowerCase()}`}>{whatsappStatusLabel(item)}</span>{item.status === "FAILED" && <button className="ghost" onClick={() => resendWhatsapp(item.id)}>إعادة الإرسال</button>}</article>)}</section>}
      {session.user.permissions.includes("printer.manage") && <section className="history"><h3>مهام الطباعة</h3>{detail.printJobs.map((job) => <article key={job.id}><b>{job.kind === "LABEL" ? "ملصق" : "إيصال"} · {printStatusLabel[job.status] ?? job.status}</b><button className="ghost" onClick={() => reprint(job.id)}>إعادة الطباعة</button></article>)}</section>}
      <section className="history"><h3>السجل</h3>{detail.notes.map((item) => <article key={item.id}><b>{item.type === "DIAGNOSTIC" ? "تشخيص" : "ملاحظة داخلية"} · {item.author.name}</b><p>{item.body}</p></article>)}{detail.quotes.map((item) => <article key={item.id}><b>عرض سعر #{item.version} · {formatMoney(item.amount)}</b><p>{item.diagnosis} · {item.status}</p></article>)}{detail.statusHistory.slice().reverse().map((item) => <article key={item.id}><b>{statusLabels[item.toStatus]}</b><small>{new Date(item.createdAt).toLocaleString("ar-EG")} {item.reason && `· ${item.reason}`}</small></article>)}</section>
    </div>}
  </>;
}
