import type { FastifyInstance } from "fastify";
import { PaymentMethod, Prisma, type PrismaClient } from "../../generated/client/index.js";
import { z } from "zod";
import { assertTransition } from "@repair/domain";
import { requireAuth, requirePermission } from "../lib/auth.js";
import { createPublicToken, hashRequest, hashToken } from "../lib/crypto.js";
import { dispatchWhatsappMessage, queueLifecycleMessage, trackingUrlFromPrintJobs } from "../services/whatsapp-lifecycle.js";
import { approvalBaseUrl, approvedCharge, httpError, moneyInput, paidTotal, statusSchema } from "./shared.js";

const whatsappResult = (status: string) => status === "SENT" ? "تم تحديث حالة الجهاز وإرسال رسالة واتساب." : status === "FAILED" ? "تم تحديث حالة الجهاز، ولكن تعذر إرسال رسالة واتساب." : status === "INVALID_PHONE" ? "تم تحديث حالة الجهاز، لكن رقم واتساب غير صالح." : "تم تحديث حالة الجهاز، والرسالة في انتظار الإرسال.";

export function registerWorkflowRoutes(app: FastifyInstance, prisma: PrismaClient) {
  app.post("/repairs/:id/status", async (request) => {
    const auth = await requireAuth(request); requirePermission(auth, "repair.status.change");
    const { id } = z.object({ id: z.string().uuid() }).parse(request.params);
    const body = z.object({ status: statusSchema, reason: z.string().max(500).optional() }).parse(request.body);
    if (["CUSTOMER_APPROVED", "CUSTOMER_DECLINED", "DELIVERED"].includes(body.status)) throw httpError(422, "استخدم إجراء موافقة العميل أو التسليم المخصص");
    const repair = await prisma.repairOrder.findFirst({ where: { id, tenantId: auth.tenantId, ...(auth.branchId ? { branchId: auth.branchId } : {}) }, include: { customer: true, brand: true, branch: true, tenant: true, payments: true, quotes: { orderBy: { version: "desc" } }, printJobs: { orderBy: { createdAt: "asc" } } } });
    if (!repair) throw httpError(404, "أمر الصيانة غير موجود");
    assertTransition(repair.status, body.status);
    const transaction = await prisma.$transaction(async (tx) => {
      const updated = await tx.repairOrder.update({ where: { id }, data: { status: body.status } });
      await tx.repairStatusHistory.create({ data: { repairOrderId: id, fromStatus: repair.status, toStatus: body.status, reason: body.reason, changedById: auth.userId } });
      let messageId: string | null = null; let queueStatus = "NOT_REQUIRED";
      if (body.status === "UNDER_REPAIR" || body.status === "READY_FOR_DELIVERY") {
        const finalAmount = approvedCharge(repair.quotes, Number(repair.estimatedCost)); const paidAmount = paidTotal(repair.payments);
        const queued = await queueLifecycleMessage(tx, { event: body.status, repairId: id, tenantId: auth.tenantId, branchId: repair.branchId, phone: repair.customer.phoneNormalized, whatsappPhone: repair.customer.whatsappPhone, actorId: auth.userId, customerName: repair.customer.name, shopName: repair.tenant.name, shopPhone: repair.tenant.phone, branchName: repair.branch.name, repairNumber: repair.repairNumber, brand: repair.brand.name, model: repair.model, trackingUrl: trackingUrlFromPrintJobs(repair.printJobs), finalAmount, paidAmount, remainingAmount: Math.max(0, finalAmount - paidAmount), idempotencyKey: `repair:${id}:lifecycle:${body.status}` });
        messageId = queued.messageId; queueStatus = queued.status;
      }
      await tx.auditLog.create({ data: { tenantId: auth.tenantId, actorId: auth.userId, action: "repair.status_changed", entityType: "repair_order", entityId: id, before: { status: repair.status }, after: { status: body.status } } });
      await tx.systemEvent.create({ data: { tenantId: auth.tenantId, branchId: repair.branchId, type: body.status === "READY_FOR_DELIVERY" ? "repair.ready_for_delivery" : "repair.status.changed", entityId: id, payload: { repairNumber: repair.repairNumber, from: repair.status, to: body.status } } });
      return { updated, messageId, queueStatus };
    });
    const delivery = transaction.messageId ? await dispatchWhatsappMessage(prisma, transaction.messageId, auth.userId).catch(() => ({ status: "PENDING" as const })) : { status: transaction.queueStatus };
    return { ...transaction.updated, whatsappStatus: delivery.status, message: whatsappResult(delivery.status) };
  });

  app.post("/repairs/:id/status/correct", async (request) => {
    const auth = await requireAuth(request); requirePermission(auth, "repair.status.correct");
    const { id } = z.object({ id: z.string().uuid() }).parse(request.params); const body = z.object({ status: statusSchema, reason: z.string().trim().min(5).max(500) }).parse(request.body);
    const repair = await prisma.repairOrder.findFirst({ where: { id, tenantId: auth.tenantId, ...(auth.branchId ? { branchId: auth.branchId } : {}) } }); if (!repair) throw httpError(404, "أمر الصيانة غير موجود"); if (repair.status === body.status) throw httpError(409, "الحالة الجديدة مطابقة للحالة الحالية");
    return prisma.$transaction(async (tx) => { const updated = await tx.repairOrder.update({ where: { id }, data: { status: body.status } }); await tx.repairStatusHistory.create({ data: { repairOrderId: id, fromStatus: repair.status, toStatus: body.status, reason: `تصحيح إداري: ${body.reason}`, changedById: auth.userId } }); await tx.auditLog.create({ data: { tenantId: auth.tenantId, actorId: auth.userId, action: "repair.status_corrected", entityType: "repair_order", entityId: id, before: { status: repair.status }, after: { status: body.status, reason: body.reason } } }); await tx.systemEvent.create({ data: { tenantId: auth.tenantId, branchId: repair.branchId, type: "repair.status.changed", entityId: id, payload: { from: repair.status, to: body.status, correction: true } } }); return updated; });
  });

  app.post("/repairs/:id/notes", async (request, reply) => { const auth = await requireAuth(request); requirePermission(auth, "repair.edit"); const { id } = z.object({ id: z.string().uuid() }).parse(request.params); const body = z.object({ type: z.enum(["DIAGNOSTIC", "INTERNAL"]), body: z.string().trim().min(2).max(3000) }).parse(request.body); const repair = await prisma.repairOrder.findFirst({ where: { id, tenantId: auth.tenantId, ...(auth.branchId ? { branchId: auth.branchId } : {}) } }); if (!repair) throw httpError(404, "أمر الصيانة غير موجود"); return reply.status(201).send(await prisma.repairNote.create({ data: { repairOrderId: id, authorId: auth.userId, type: body.type, body: body.body }, include: { author: { select: { name: true } } } })); });

  app.get("/workshop/technicians", async (request) => { const auth = await requireAuth(request); requirePermission(auth, "workshop.access"); return prisma.user.findMany({ where: { tenantId: auth.tenantId, isActive: true, ...(auth.branchId ? { OR: [{ branchId: auth.branchId }, { branchId: null }] } : {}), roles: { some: { role: { permissions: { some: { permissionId: "workshop.access" } } } } } }, select: { id: true, name: true, branchId: true }, orderBy: { name: "asc" } }); });

  app.post("/repairs/:id/assign", async (request, reply) => { const auth = await requireAuth(request); requirePermission(auth, "repair.edit"); const { id } = z.object({ id: z.string().uuid() }).parse(request.params); const { technicianId } = z.object({ technicianId: z.string().uuid() }).parse(request.body); const [repair, technician] = await Promise.all([prisma.repairOrder.findFirst({ where: { id, tenantId: auth.tenantId, ...(auth.branchId ? { branchId: auth.branchId } : {}) } }), prisma.user.findFirst({ where: { id: technicianId, tenantId: auth.tenantId, isActive: true, ...(auth.branchId ? { OR: [{ branchId: auth.branchId }, { branchId: null }] } : {}) } })]); if (!repair || !technician) throw httpError(404, "أمر الصيانة أو الفني غير موجود"); const assignment = await prisma.$transaction(async (tx) => { await tx.repairAssignment.updateMany({ where: { repairOrderId: id, endedAt: null }, data: { endedAt: new Date() } }); const created = await tx.repairAssignment.create({ data: { repairOrderId: id, technicianId, assignedById: auth.userId } }); await tx.auditLog.create({ data: { tenantId: auth.tenantId, actorId: auth.userId, action: "repair.assigned", entityType: "repair_order", entityId: id, after: { technicianId } } }); return created; }); return reply.status(201).send(assignment); });

  app.post("/repairs/:id/quotes", async (request, reply) => {
    const auth = await requireAuth(request); requirePermission(auth, "repair.quote.create"); const { id } = z.object({ id: z.string().uuid() }).parse(request.params); const body = z.object({ amount: moneyInput, diagnosis: z.string().trim().min(3).max(3000), customerNote: z.string().max(1000).optional() }).parse(request.body);
    const repair = await prisma.repairOrder.findFirst({ where: { id, tenantId: auth.tenantId, ...(auth.branchId ? { branchId: auth.branchId } : {}) }, include: { customer: true, brand: true, branch: true, tenant: true, printJobs: { orderBy: { createdAt: "asc" } }, quotes: { orderBy: { version: "desc" } } } });
    if (!repair) throw httpError(404, "أمر الصيانة غير موجود"); if (["DELIVERED", "CANCELLED", "READY_FOR_DELIVERY", "READY_FOR_RETURN_WITHOUT_REPAIR"].includes(repair.status)) throw httpError(409, "لا يمكن إنشاء عرض سعر في الحالة الحالية");
    const token = createPublicToken(); const version = (repair.quotes[0]?.version ?? 0) + 1; const approvalUrl = `${approvalBaseUrl()}/approve/${token}`;
    const transaction = await prisma.$transaction(async (tx) => {
      await tx.repairQuote.updateMany({ where: { repairOrderId: id, status: "PENDING" }, data: { status: "SUPERSEDED" } });
      const created = await tx.repairQuote.create({ data: { repairOrderId: id, version, amount: new Prisma.Decimal(body.amount), diagnosis: body.diagnosis, customerNote: body.customerNote, approvalTokenHash: hashToken(token), createdById: auth.userId } });
      if (repair.status !== "AWAITING_CUSTOMER_APPROVAL") { await tx.repairOrder.update({ where: { id }, data: { status: "AWAITING_CUSTOMER_APPROVAL" } }); await tx.repairStatusHistory.create({ data: { repairOrderId: id, fromStatus: repair.status, toStatus: "AWAITING_CUSTOMER_APPROVAL", reason: `عرض سعر رقم ${version}`, changedById: auth.userId } }); }
      const queued = await queueLifecycleMessage(tx, { event: "AWAITING_CUSTOMER_APPROVAL", repairId: id, tenantId: auth.tenantId, branchId: repair.branchId, phone: repair.customer.phoneNormalized, whatsappPhone: repair.customer.whatsappPhone, actorId: auth.userId, customerName: repair.customer.name, shopName: repair.tenant.name, shopPhone: repair.tenant.phone, branchName: repair.branch.name, repairNumber: repair.repairNumber, brand: repair.brand.name, model: repair.model, diagnosis: body.diagnosis, finalAmount: body.amount, approvalUrl, trackingUrl: trackingUrlFromPrintJobs(repair.printJobs), idempotencyKey: `repair:${id}:approval:quote:${version}` });
      await tx.auditLog.create({ data: { tenantId: auth.tenantId, actorId: auth.userId, action: "repair.quote_created", entityType: "repair_quote", entityId: created.id, after: { repairOrderId: id, version, amount: body.amount } } }); await tx.systemEvent.create({ data: { tenantId: auth.tenantId, branchId: repair.branchId, type: "quote.created", entityId: id, payload: { repairNumber: repair.repairNumber, version } } });
      return { created, messageId: queued.messageId, queueStatus: queued.status };
    });
    const delivery = transaction.messageId ? await dispatchWhatsappMessage(prisma, transaction.messageId, auth.userId).catch(() => ({ status: "PENDING" as const })) : { status: transaction.queueStatus };
    return reply.status(201).send({ id: transaction.created.id, version, amount: Number(transaction.created.amount), status: transaction.created.status, approvalUrl, whatsappStatus: delivery.status, message: whatsappResult(delivery.status) });
  });

  app.post("/repairs/:id/whatsapp/resend", async (request) => {
    const auth = await requireAuth(request); requirePermission(auth, "whatsapp.manage"); const { id } = z.object({ id: z.string().uuid() }).parse(request.params); const body = z.object({ messageId: z.string().uuid().optional() }).parse(request.body ?? {});
    const repair = await prisma.repairOrder.findFirst({ where: { id, tenantId: auth.tenantId, ...(auth.branchId ? { branchId: auth.branchId } : {}) }, include: { whatsappMessages: { orderBy: { createdAt: "desc" } } } }); if (!repair) throw httpError(404, "أمر الصيانة غير موجود");
    const source = body.messageId ? repair.whatsappMessages.find((item) => item.id === body.messageId) : repair.whatsappMessages[0]; if (!source) throw httpError(409, "لا توجد رسالة محفوظة لإعادة إرسالها");
    const resent = await prisma.$transaction(async (tx) => { const created = await tx.whatsappMessage.create({ data: { repairOrderId: repair.id, tenantId: auth.tenantId, branchId: repair.branchId, type: `${source.type}_RESEND`, recipient: source.recipient, templateKey: source.templateKey, variables: source.variables === null ? Prisma.JsonNull : source.variables, idempotencyKey: `repair:${repair.id}:manual:${source.id}:${crypto.randomUUID()}` } }); await tx.auditLog.create({ data: { tenantId: auth.tenantId, actorId: auth.userId, action: "whatsapp.manual_resend", entityType: "whatsapp_message", entityId: created.id, after: { sourceMessageId: source.id, templateKey: source.templateKey } } }); return created; });
    const delivery = await dispatchWhatsappMessage(prisma, resent.id, auth.userId).catch(() => ({ status: "PENDING" as const })); return { success: true, messageId: resent.id, status: delivery.status };
  });

  app.post("/repairs/:id/deliver", async (request, reply) => {
    const auth = await requireAuth(request); requirePermission(auth, "delivery.complete"); requirePermission(auth, "payment.create"); const { id } = z.object({ id: z.string().uuid() }).parse(request.params); const body = z.object({ collectedAmount: moneyInput.default("0"), paymentMethod: z.nativeEnum(PaymentMethod).default("CASH"), reference: z.string().max(120).optional() }).parse(request.body);
    const key = z.string().min(8).max(200).parse(request.headers["idempotency-key"]); const requestHash = hashRequest(body); const prior = await prisma.idempotencyKey.findUnique({ where: { tenantId_key: { tenantId: auth.tenantId, key } } }); if (prior) { if (prior.requestHash !== requestHash) return reply.status(409).send({ error: "مفتاح العملية مستخدم لطلب مختلف" }); if (prior.response) return prior.response; return reply.status(409).send({ error: "العملية قيد التنفيذ" }); }
    try { await prisma.idempotencyKey.create({ data: { tenantId: auth.tenantId, key, requestHash } }); } catch { return reply.status(409).send({ error: "العملية قيد التنفيذ" }); }
    try {
      const repair = await prisma.repairOrder.findFirst({ where: { id, tenantId: auth.tenantId, ...(auth.branchId ? { branchId: auth.branchId } : {}) }, include: { customer: true, brand: true, branch: true, tenant: true, printJobs: { orderBy: { createdAt: "asc" } }, payments: true, quotes: { orderBy: { version: "desc" } } } }); if (!repair) throw httpError(404, "أمر الصيانة غير موجود"); if (!["READY_FOR_DELIVERY", "READY_FOR_RETURN_WITHOUT_REPAIR"].includes(repair.status)) throw httpError(409, "الجهاز غير جاهز للتسليم");
      const finalCharge = repair.status === "READY_FOR_RETURN_WITHOUT_REPAIR" ? 0 : approvedCharge(repair.quotes, Number(repair.estimatedCost)); const paid = paidTotal(repair.payments); const remaining = Math.max(0, finalCharge - paid); const collected = Number(new Prisma.Decimal(body.collectedAmount)); if (Math.abs(collected - remaining) > 0.001) throw httpError(422, `المبلغ المطلوب تحصيله هو ${remaining.toFixed(2)}`);
      const transaction = await prisma.$transaction(async (tx) => {
        if (collected > 0) { const payment = await tx.payment.create({ data: { repairOrderId: id, amount: new Prisma.Decimal(body.collectedAmount), kind: "COLLECTION", paymentMethod: body.paymentMethod, reference: body.reference, createdById: auth.userId } }); const shift = await tx.cashShift.findFirst({ where: { tenantId: auth.tenantId, branchId: repair.branchId, status: "OPEN" } }); await tx.cashTransaction.create({ data: { tenantId: auth.tenantId, branchId: repair.branchId, shiftId: shift?.id, employeeId: auth.userId, type: "COLLECTION", direction: "IN", amount: new Prisma.Decimal(body.collectedAmount), paymentMethod: body.paymentMethod, sourceType: "repair_payment", sourceId: id, paymentId: payment.id, reference: body.reference } }); }
        const deliveredAt = new Date(); await tx.repairOrder.update({ where: { id }, data: { status: "DELIVERED", deliveredAt, unlockKind: null, unlockCiphertext: null, unlockIv: null, unlockAuthTag: null } }); await tx.repairStatusHistory.create({ data: { repairOrderId: id, fromStatus: repair.status, toStatus: "DELIVERED", reason: "تم التسليم والتحصيل", changedById: auth.userId } }); await tx.printJob.create({ data: { repairOrderId: id, kind: "DELIVERY_RECEIPT", payload: { paperWidth: "80mm", repairNumber: repair.repairNumber, customer: repair.customer.name, device: `${repair.brand.name} ${repair.model}`, finalCharge, previouslyPaid: paid, collected, remaining: 0, deliveredAt } } });
        const queued = await queueLifecycleMessage(tx, { event: "DELIVERED", repairId: id, tenantId: auth.tenantId, branchId: repair.branchId, phone: repair.customer.phoneNormalized, whatsappPhone: repair.customer.whatsappPhone, actorId: auth.userId, customerName: repair.customer.name, shopName: repair.tenant.name, shopPhone: repair.tenant.phone, branchName: repair.branch.name, repairNumber: repair.repairNumber, brand: repair.brand.name, model: repair.model, trackingUrl: trackingUrlFromPrintJobs(repair.printJobs), finalAmount: finalCharge, paidAmount: paid + collected, remainingAmount: 0, idempotencyKey: `repair:${id}:lifecycle:DELIVERED` });
        await tx.auditLog.create({ data: { tenantId: auth.tenantId, actorId: auth.userId, action: "repair.delivered", entityType: "repair_order", entityId: id, before: { status: repair.status, paid }, after: { status: "DELIVERED", finalCharge, collected, unlockPurged: true } } }); await tx.systemEvent.create({ data: { tenantId: auth.tenantId, branchId: repair.branchId, type: "repair.delivered", entityId: id, payload: { repairNumber: repair.repairNumber, status: "DELIVERED" } } });
        return { response: { success: true, repairId: id, repairNumber: repair.repairNumber, status: "DELIVERED", finalCharge, paid: paid + collected, remaining: 0 }, messageId: queued.messageId, queueStatus: queued.status };
      });
      const delivery = transaction.messageId ? await dispatchWhatsappMessage(prisma, transaction.messageId, auth.userId).catch(() => ({ status: "PENDING" as const })) : { status: transaction.queueStatus }; const result = { ...transaction.response, whatsappStatus: delivery.status, message: whatsappResult(delivery.status) }; await prisma.idempotencyKey.update({ where: { tenantId_key: { tenantId: auth.tenantId, key } }, data: { response: result } }); return result;
    } catch (error) { await prisma.idempotencyKey.deleteMany({ where: { tenantId: auth.tenantId, key, response: { equals: Prisma.JsonNull } } }); throw error; }
  });
}
