import { beforeAll, describe, expect, it, vi } from "vitest";
import type { PrismaClient } from "../generated/client/index.js";
let buildApp: typeof import("./app.js").buildApp;
beforeAll(async () => { ({ buildApp } = await import("./app.js")); });
const payload = { owner: { fullName: "مالك مركز الاختبار", username: "testowner", email: "owner@setup.local", phone: "01012345678", whatsapp: "01012345678", password: "SecurePass123" }, shop: { name: "مركز اختبار الإعداد", code: "setup-test", phone: "01012345678", whatsapp: "01012345678", address: "القاهرة", governorate: "القاهرة", city: "القاهرة", notes: "اختبار" }, branches: [{ name: "الفرع الرئيسي", code: "MAIN", address: "القاهرة", phone: "01012345678", workstations: [{ name: "الاستقبال", type: "RECEPTION", count: 2, defaultPage: "dashboard" }] }], defaults: { currency: "EGP", timezone: "Africa/Cairo", paperWidth: "80mm", warrantyDays: 30, whatsappMode: "later" }, subscription: { planCode: "STARTER", billingCycle: "TRIAL" }, acceptedTerms: true };
function fixture(options: { existingTenant?: boolean } = {}) {
  let saved: Record<string, unknown> | null = null; const workstationCreateMany = vi.fn();
  const tx: any = { onboardingRequest: { create: vi.fn(async ({ data }: any) => { saved = { ...data, response: null }; }), update: vi.fn(async ({ data }: any) => { saved = { ...(saved ?? {}), response: data.response }; }) }, plan: { upsert: vi.fn().mockResolvedValue({ id: "plan", code: "STARTER" }) }, tenant: { create: vi.fn().mockResolvedValue({ id: "tenant", slug: "setup-test" }) }, branch: { create: vi.fn().mockResolvedValue({ id: "branch" }) }, workstation: { createMany: workstationCreateMany }, permission: { upsert: vi.fn() }, role: { create: vi.fn().mockResolvedValue({ id: "role" }) }, user: { create: vi.fn().mockResolvedValue({ id: "user", username: "testowner", email: "owner@setup.local" }) }, deviceBrand: { createMany: vi.fn() }, faultPreset: { createMany: vi.fn() }, subscription: { create: vi.fn() }, auditLog: { create: vi.fn() } };
  const prisma: any = { plan: { findMany: vi.fn().mockResolvedValue([]) }, tenant: { findUnique: vi.fn().mockResolvedValue(options.existingTenant ? { id: "existing" } : null) }, onboardingRequest: { findUnique: vi.fn(async () => saved) }, $transaction: vi.fn((callback: any) => callback(tx)) };
  return { app: buildApp(prisma as PrismaClient), workstationCreateMany };
}
describe("public first-time setup", () => {
  it("creates the tenant atomically with branches and expanded workstations, then safely replays the response", async () => { const { app, workstationCreateMany } = fixture(); const request = { method: "POST" as const, url: "/public/setup", headers: { "idempotency-key": "550e8400-e29b-41d4-a716-446655440000" }, payload }; const first = await app.inject(request); const second = await app.inject(request); await app.close(); expect(first.statusCode).toBe(201); expect(second.statusCode).toBe(200); expect(first.json()).toMatchObject({ success: true, centerCode: "setup-test", identity: "testowner" }); expect(workstationCreateMany).toHaveBeenCalledWith(expect.objectContaining({ data: expect.arrayContaining([expect.objectContaining({ name: "الاستقبال 1" }), expect.objectContaining({ name: "الاستقبال 2" })]) })); });
  it("rejects a duplicate center code before creating anything", async () => { const { app } = fixture({ existingTenant: true }); const response = await app.inject({ method: "POST", url: "/public/setup", headers: { "idempotency-key": "550e8400-e29b-41d4-a716-446655440001" }, payload }); await app.close(); expect(response.statusCode).toBe(409); expect(response.json()).toMatchObject({ code: "CENTER_CODE_TAKEN" }); });
  it("returns the exact invalid phone field instead of a login error", async () => { const { app } = fixture(); const response = await app.inject({ method: "POST", url: "/public/setup", headers: { "idempotency-key": "550e8400-e29b-41d4-a716-446655440003" }, payload: { ...payload, shop: { ...payload.shop, phone: "151515" } } }); await app.close(); expect(response.statusCode).toBe(422); expect(response.json()).toMatchObject({ code: "SETUP_VALIDATION_ERROR", message: expect.stringContaining("هاتف المركز") }); });
  it("requires review confirmation", async () => { const { app } = fixture(); const response = await app.inject({ method: "POST", url: "/public/setup", headers: { "idempotency-key": "550e8400-e29b-41d4-a716-446655440002" }, payload: { ...payload, acceptedTerms: false } }); await app.close(); expect(response.statusCode).toBe(422); expect(response.headers["content-type"]).toContain("application/json"); });
});


