import { describe, expect, it, vi } from "vitest";
import type { Prisma } from "../generated/client/index.js";
import { defaultLifecycleTemplates, lifecycleMessageDefinitions, queueLifecycleMessage, renderLifecycleTemplate, templateValidationErrors } from "./services/whatsapp-lifecycle.js";

const base = { repairId: "11111111-1111-4111-8111-111111111111", tenantId: "22222222-2222-4222-8222-222222222222", branchId: "33333333-3333-4333-8333-333333333333", phone: "01012345678", customerName: "أحمد", shopName: "المركز", branchName: "الرئيسي", repairNumber: "REP-2026-000001", brand: "Samsung", model: "A54", idempotencyKey: "test-key" };
function transaction(existing: { id: string } | null = null) { return { whatsappMessage: { findUnique: vi.fn().mockResolvedValue(existing), upsert: vi.fn().mockResolvedValue(existing ?? { id: "message-1" }) }, auditLog: { create: vi.fn() } } as unknown as Prisma.TransactionClient; }

describe("central WhatsApp lifecycle", () => {
  it("maps every required repair event to one deterministic template", () => expect(Object.entries(lifecycleMessageDefinitions).map(([event, definition]) => [event, definition.templateKey])).toEqual([["RECEIVED", "device_received"], ["AWAITING_CUSTOMER_APPROVAL", "waiting_approval"], ["UNDER_REPAIR", "under_repair"], ["READY_FOR_DELIVERY", "ready_for_delivery"], ["DELIVERED", "delivered"]]));
  it.each(Object.keys(lifecycleMessageDefinitions) as (keyof typeof lifecycleMessageDefinitions)[])("queues exactly one %s automatic message", async (event) => { const tx = transaction(); await queueLifecycleMessage(tx, { ...base, event, diagnosis: "شاشة", approvalUrl: "https://example.test/approve/token", trackingUrl: "https://example.test/r/token", finalAmount: 900, paidAmount: 200, remainingAmount: 700 }); expect(tx.whatsappMessage.upsert).toHaveBeenCalledTimes(1); expect((tx.whatsappMessage.upsert as ReturnType<typeof vi.fn>).mock.calls[0]![0].create.templateKey).toBe(lifecycleMessageDefinitions[event].templateKey); });
  it("queues READY once with ordered variables and an explicit zero balance message", async () => { const tx = transaction(); await queueLifecycleMessage(tx, { ...base, event: "READY_FOR_DELIVERY", finalAmount: 900, paidAmount: 900, remainingAmount: 0 }); const create = (tx.whatsappMessage.upsert as ReturnType<typeof vi.fn>).mock.calls[0]![0].create; expect(Object.keys(create.variables)).toEqual(lifecycleMessageDefinitions.READY_FOR_DELIVERY.variables); expect(create.variables.remainingAmount).toBe("لا يوجد مبلغ متبقٍ."); expect(tx.auditLog.create).toHaveBeenCalledTimes(1); });
  it("does not create a second queue audit for an existing idempotency key", async () => { const tx = transaction({ id: "message-1" }); await queueLifecycleMessage(tx, { ...base, event: "RECEIVED" }); expect(tx.auditLog.create).not.toHaveBeenCalled(); });
  it("does not fail the repair workflow when the WhatsApp number is invalid", async () => { const tx = transaction(); const result = await queueLifecycleMessage(tx, { ...base, phone: "+20201012345678", event: "RECEIVED" }); expect(result).toEqual({ messageId: null, status: "INVALID_PHONE" }); expect(tx.whatsappMessage.upsert).not.toHaveBeenCalled(); expect(tx.auditLog.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ action: "whatsapp.automatic_skipped" }) })); });
  it("validates variables and renders an Arabic preview without unknown placeholders", () => { expect(templateValidationErrors(defaultLifecycleTemplates)).toEqual([]); expect(templateValidationErrors({ device_received: "{unknown}" })).toContain("المتغير {unknown} غير مدعوم في device_received"); expect(renderLifecycleTemplate("مرحباً {customerName}", { customerName: "أحمد" })).toBe("مرحباً أحمد"); });
});
